/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision â€” parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AccessToken,
  DerivLoginRequest,
  Error,
  LoginRequest,
  MessageResponse,
  OAuthLoginRequest,
  RefreshRequest,
  RegisterRequest,
  RegisterResponse,
  ResendOTPRequest,
  TokenPair,
  ValidationErrorResponse,
  VerifyEmailRequest,
  VerifyOTPRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType , BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a FXNod account and emits a USER_CREATED event to the Referral service.
 * @summary Register a new account
 */
export const register = (
    registerRequest: BodyType<RegisterRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterResponse>(
      {url: `/api/v1/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequest, signal
    },
      options);
    }
  


export const getRegisterMutationOptions = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterRequest>}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: BodyType<RegisterRequest>}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = BodyType<RegisterRequest>
    export type RegisterMutationError = ErrorType<Error | ValidationErrorResponse>

    /**
 * @summary Register a new account
 */
export const useRegister = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: BodyType<RegisterRequest>},
        TContext
      > => {

      const mutationOptions = getRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Authenticates and returns an access/refresh token pair. Also sets the
refresh token as an httpOnly cookie for browsers. Rate-limited per client IP.

 * @summary Log in
 */
export const login = (
    loginRequest: BodyType<LoginRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenPair>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getLoginMutationOptions = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginRequest>}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: BodyType<LoginRequest>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<LoginRequest>
    export type LoginMutationError = ErrorType<Error | ValidationErrorResponse>

    /**
 * @summary Log in
 */
export const useLogin = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: BodyType<LoginRequest>},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Exchanges a valid refresh token (httpOnly cookie preferred, body fallback)
for a new access token.

 * @summary Refresh access token
 */
export const refreshToken = (
    refreshRequest?: BodyType<RefreshRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AccessToken>(
      {url: `/api/v1/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest, signal
    },
      options);
    }
  


export const getRefreshTokenMutationOptions = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: BodyType<RefreshRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: BodyType<RefreshRequest>}, TContext> => {

const mutationKey = ['refreshToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, {data: BodyType<RefreshRequest>}> = (props) => {
          const {data} = props ?? {};

          return  refreshToken(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
    export type RefreshTokenMutationBody = BodyType<RefreshRequest>
    export type RefreshTokenMutationError = ErrorType<Error>

    /**
 * @summary Refresh access token
 */
export const useRefreshToken = <TError = ErrorType<Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: BodyType<RefreshRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshToken>>,
        TError,
        {data: BodyType<RefreshRequest>},
        TContext
      > => {

      const mutationOptions = getRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Verify email address
 */
export const verifyEmail = (
    verifyEmailRequest: BodyType<VerifyEmailRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MessageResponse>(
      {url: `/api/v1/auth/verify-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyEmailRequest, signal
    },
      options);
    }
  


export const getVerifyEmailMutationOptions = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyEmail>>, TError,{data: BodyType<VerifyEmailRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyEmail>>, TError,{data: BodyType<VerifyEmailRequest>}, TContext> => {

const mutationKey = ['verifyEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyEmail>>, {data: BodyType<VerifyEmailRequest>}> = (props) => {
          const {data} = props ?? {};

          return  verifyEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyEmailMutationResult = NonNullable<Awaited<ReturnType<typeof verifyEmail>>>
    export type VerifyEmailMutationBody = BodyType<VerifyEmailRequest>
    export type VerifyEmailMutationError = ErrorType<Error | ValidationErrorResponse>

    /**
 * @summary Verify email address
 */
export const useVerifyEmail = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyEmail>>, TError,{data: BodyType<VerifyEmailRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyEmail>>,
        TError,
        {data: BodyType<VerifyEmailRequest>},
        TContext
      > => {

      const mutationOptions = getVerifyEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Confirms an account using the 6-digit code emailed at registration and
establishes a session â€” returns an access/refresh token pair and sets
the httpOnly refresh cookie, same shape as login. Runs alongside the
magic-link flow; either verifies the account. Rate-limited per client
IP; failure responses are uniform to prevent account enumeration.

 * @summary Verify account with a numeric OTP (and log in)
 */
export const verifyOtp = (
    verifyOTPRequest: BodyType<VerifyOTPRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenPair>(
      {url: `/api/v1/auth/verify-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyOTPRequest, signal
    },
      options);
    }
  


export const getVerifyOtpMutationOptions = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyOtp>>, TError,{data: BodyType<VerifyOTPRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyOtp>>, TError,{data: BodyType<VerifyOTPRequest>}, TContext> => {

const mutationKey = ['verifyOtp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyOtp>>, {data: BodyType<VerifyOTPRequest>}> = (props) => {
          const {data} = props ?? {};

          return  verifyOtp(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyOtpMutationResult = NonNullable<Awaited<ReturnType<typeof verifyOtp>>>
    export type VerifyOtpMutationBody = BodyType<VerifyOTPRequest>
    export type VerifyOtpMutationError = ErrorType<Error | ValidationErrorResponse>

    /**
 * @summary Verify account with a numeric OTP (and log in)
 */
export const useVerifyOtp = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyOtp>>, TError,{data: BodyType<VerifyOTPRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyOtp>>,
        TError,
        {data: BodyType<VerifyOTPRequest>},
        TContext
      > => {

      const mutationOptions = getVerifyOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Reissues a code for an existing, un-verified account (subject to a
cooldown). Always returns 200 to avoid account enumeration.

 * @summary Resend a verification OTP
 */
export const resendOtp = (
    resendOTPRequest: BodyType<ResendOTPRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MessageResponse>(
      {url: `/api/v1/auth/resend-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resendOTPRequest, signal
    },
      options);
    }
  


export const getResendOtpMutationOptions = <TError = ErrorType<ValidationErrorResponse | Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resendOtp>>, TError,{data: BodyType<ResendOTPRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resendOtp>>, TError,{data: BodyType<ResendOTPRequest>}, TContext> => {

const mutationKey = ['resendOtp'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resendOtp>>, {data: BodyType<ResendOTPRequest>}> = (props) => {
          const {data} = props ?? {};

          return  resendOtp(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResendOtpMutationResult = NonNullable<Awaited<ReturnType<typeof resendOtp>>>
    export type ResendOtpMutationBody = BodyType<ResendOTPRequest>
    export type ResendOtpMutationError = ErrorType<ValidationErrorResponse | Error>

    /**
 * @summary Resend a verification OTP
 */
export const useResendOtp = <TError = ErrorType<ValidationErrorResponse | Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resendOtp>>, TError,{data: BodyType<ResendOTPRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resendOtp>>,
        TError,
        {data: BodyType<ResendOTPRequest>},
        TContext
      > => {

      const mutationOptions = getResendOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Verifies a provider credential, links it to a primary account (or
creates a passwordless one), and returns a token pair + refresh cookie.
First-time social users skip OTP and land on the dashboard.

 * @summary Social sign-in (Google / Apple / Facebook)
 */
export const oauthLogin = (
    provider: 'google' | 'apple' | 'facebook',
    oAuthLoginRequest: BodyType<OAuthLoginRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenPair>(
      {url: `/api/v1/auth/oauth/${provider}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: oAuthLoginRequest, signal
    },
      options);
    }
  


export const getOauthLoginMutationOptions = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof oauthLogin>>, TError,{provider: 'google' | 'apple' | 'facebook';data: BodyType<OAuthLoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof oauthLogin>>, TError,{provider: 'google' | 'apple' | 'facebook';data: BodyType<OAuthLoginRequest>}, TContext> => {

const mutationKey = ['oauthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof oauthLogin>>, {provider: 'google' | 'apple' | 'facebook';data: BodyType<OAuthLoginRequest>}> = (props) => {
          const {provider,data} = props ?? {};

          return  oauthLogin(provider,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OauthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof oauthLogin>>>
    export type OauthLoginMutationBody = BodyType<OAuthLoginRequest>
    export type OauthLoginMutationError = ErrorType<Error | ValidationErrorResponse>

    /**
 * @summary Social sign-in (Google / Apple / Facebook)
 */
export const useOauthLogin = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof oauthLogin>>, TError,{provider: 'google' | 'apple' | 'facebook';data: BodyType<OAuthLoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof oauthLogin>>,
        TError,
        {provider: 'google' | 'apple' | 'facebook';data: BodyType<OAuthLoginRequest>},
        TContext
      > => {

      const mutationOptions = getOauthLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Revokes the session for the refresh token (cookie or body) and clears the cookie. Idempotent.
 * @summary Log out
 */
export const logout = (
    refreshRequest?: BodyType<RefreshRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<MessageResponse>(
      {url: `/api/v1/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest, signal
    },
      options);
    }
  


export const getLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: BodyType<RefreshRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: BodyType<RefreshRequest>}, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, {data: BodyType<RefreshRequest>}> = (props) => {
          const {data} = props ?? {};

          return  logout(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    export type LogoutMutationBody = BodyType<RefreshRequest>
    export type LogoutMutationError = ErrorType<unknown>

    /**
 * @summary Log out
 */
export const useLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: BodyType<RefreshRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        {data: BodyType<RefreshRequest>},
        TContext
      > => {

      const mutationOptions = getLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * PUBLIC (no bearer). Mints an FXNod session from a Deriv OAuth token:
validates the OAuth `state`, finds-or-creates the FXNod user keyed by the
Deriv account, stores the encrypted Deriv token (account linking), sets
the httpOnly refresh cookie, and returns an access token â€” same session
shape as /api/v1/auth/login.

 * @summary Log in with Deriv OAuth
 */
export const loginWithDeriv = (
    derivLoginRequest: BodyType<DerivLoginRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenPair>(
      {url: `/api/v1/auth/deriv`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: derivLoginRequest, signal
    },
      options);
    }
  


export const getLoginWithDerivMutationOptions = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithDeriv>>, TError,{data: BodyType<DerivLoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginWithDeriv>>, TError,{data: BodyType<DerivLoginRequest>}, TContext> => {

const mutationKey = ['loginWithDeriv'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginWithDeriv>>, {data: BodyType<DerivLoginRequest>}> = (props) => {
          const {data} = props ?? {};

          return  loginWithDeriv(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginWithDerivMutationResult = NonNullable<Awaited<ReturnType<typeof loginWithDeriv>>>
    export type LoginWithDerivMutationBody = BodyType<DerivLoginRequest>
    export type LoginWithDerivMutationError = ErrorType<Error | ValidationErrorResponse>

    /**
 * @summary Log in with Deriv OAuth
 */
export const useLoginWithDeriv = <TError = ErrorType<Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithDeriv>>, TError,{data: BodyType<DerivLoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginWithDeriv>>,
        TError,
        {data: BodyType<DerivLoginRequest>},
        TContext
      > => {

      const mutationOptions = getLoginWithDerivMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    