/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision â€” parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AutoHubRun,
  BotStartConflict,
  ListAutoHubBots200,
  ListAutoHubRunEntries200,
  ListAutoHubRunEntriesParams,
  ListAutoHubRuns200,
  ListAutoHubRunsParams,
  StartAutoHubRunRequest,
  StartAutoHubRunResponse
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType , BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Each entry says what the bot does and exactly what a start request for it may contain: how many markets, the smallest stake, and its own settings with their types and bounds. The form is rendered from this.

 * @summary List the Auto Hub bots
 */
export const listAutoHubBots = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListAutoHubBots200>(
      {url: `/api/v1/autohub/bots`, method: 'GET', signal
    },
      options);
    }
  



export const getListAutoHubBotsQueryKey = () => {
    return [
    `/api/v1/autohub/bots`
    ] as const;
    }

    
export const getListAutoHubBotsQueryOptions = <TData = Awaited<ReturnType<typeof listAutoHubBots>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubBots>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAutoHubBotsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAutoHubBots>>> = ({ signal }) => listAutoHubBots(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAutoHubBots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAutoHubBotsQueryResult = NonNullable<Awaited<ReturnType<typeof listAutoHubBots>>>
export type ListAutoHubBotsQueryError = ErrorType<unknown>


export function useListAutoHubBots<TData = Awaited<ReturnType<typeof listAutoHubBots>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubBots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutoHubBots>>,
          TError,
          Awaited<ReturnType<typeof listAutoHubBots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutoHubBots<TData = Awaited<ReturnType<typeof listAutoHubBots>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubBots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutoHubBots>>,
          TError,
          Awaited<ReturnType<typeof listAutoHubBots>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutoHubBots<TData = Awaited<ReturnType<typeof listAutoHubBots>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubBots>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the Auto Hub bots
 */

export function useListAutoHubBots<TData = Awaited<ReturnType<typeof listAutoHubBots>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubBots>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAutoHubBotsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Queues a run of one bot. The strategy, the contract and every strategy parameter not listed in the bot's `settings` come from the bot's definition and cannot be supplied. The stake is flat. Limits over a platform cap are reduced rather than refused, and returned in `limit_adjustments`.

 * @summary Start an Auto Hub bot
 */
export const startAutoHubRun = (
    botId: string,
    startAutoHubRunRequest: BodyType<StartAutoHubRunRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StartAutoHubRunResponse>(
      {url: `/api/v1/autohub/bots/${botId}/runs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startAutoHubRunRequest, signal
    },
      options);
    }
  


export const getStartAutoHubRunMutationOptions = <TError = ErrorType<void | BotStartConflict>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startAutoHubRun>>, TError,{botId: string;data: BodyType<StartAutoHubRunRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startAutoHubRun>>, TError,{botId: string;data: BodyType<StartAutoHubRunRequest>}, TContext> => {

const mutationKey = ['startAutoHubRun'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startAutoHubRun>>, {botId: string;data: BodyType<StartAutoHubRunRequest>}> = (props) => {
          const {botId,data} = props ?? {};

          return  startAutoHubRun(botId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartAutoHubRunMutationResult = NonNullable<Awaited<ReturnType<typeof startAutoHubRun>>>
    export type StartAutoHubRunMutationBody = BodyType<StartAutoHubRunRequest>
    export type StartAutoHubRunMutationError = ErrorType<void | BotStartConflict>

    /**
 * @summary Start an Auto Hub bot
 */
export const useStartAutoHubRun = <TError = ErrorType<void | BotStartConflict>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startAutoHubRun>>, TError,{botId: string;data: BodyType<StartAutoHubRunRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startAutoHubRun>>,
        TError,
        {botId: string;data: BodyType<StartAutoHubRunRequest>},
        TContext
      > => {

      const mutationOptions = getStartAutoHubRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List this user's Auto Hub runs
 */
export const listAutoHubRuns = (
    params?: ListAutoHubRunsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListAutoHubRuns200>(
      {url: `/api/v1/autohub/runs`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListAutoHubRunsQueryKey = (params?: ListAutoHubRunsParams,) => {
    return [
    `/api/v1/autohub/runs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAutoHubRunsQueryOptions = <TData = Awaited<ReturnType<typeof listAutoHubRuns>>, TError = ErrorType<unknown>>(params?: ListAutoHubRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRuns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAutoHubRunsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAutoHubRuns>>> = ({ signal }) => listAutoHubRuns(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRuns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAutoHubRunsQueryResult = NonNullable<Awaited<ReturnType<typeof listAutoHubRuns>>>
export type ListAutoHubRunsQueryError = ErrorType<unknown>


export function useListAutoHubRuns<TData = Awaited<ReturnType<typeof listAutoHubRuns>>, TError = ErrorType<unknown>>(
 params: undefined |  ListAutoHubRunsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRuns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutoHubRuns>>,
          TError,
          Awaited<ReturnType<typeof listAutoHubRuns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutoHubRuns<TData = Awaited<ReturnType<typeof listAutoHubRuns>>, TError = ErrorType<unknown>>(
 params?: ListAutoHubRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRuns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutoHubRuns>>,
          TError,
          Awaited<ReturnType<typeof listAutoHubRuns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutoHubRuns<TData = Awaited<ReturnType<typeof listAutoHubRuns>>, TError = ErrorType<unknown>>(
 params?: ListAutoHubRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRuns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List this user's Auto Hub runs
 */

export function useListAutoHubRuns<TData = Awaited<ReturnType<typeof listAutoHubRuns>>, TError = ErrorType<unknown>>(
 params?: ListAutoHubRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRuns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAutoHubRunsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Read one Auto Hub run
 */
export const getAutoHubRun = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AutoHubRun>(
      {url: `/api/v1/autohub/runs/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAutoHubRunQueryKey = (id?: string,) => {
    return [
    `/api/v1/autohub/runs/${id}`
    ] as const;
    }

    
export const getGetAutoHubRunQueryOptions = <TData = Awaited<ReturnType<typeof getAutoHubRun>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutoHubRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAutoHubRunQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAutoHubRun>>> = ({ signal }) => getAutoHubRun(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAutoHubRun>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAutoHubRunQueryResult = NonNullable<Awaited<ReturnType<typeof getAutoHubRun>>>
export type GetAutoHubRunQueryError = ErrorType<void>


export function useGetAutoHubRun<TData = Awaited<ReturnType<typeof getAutoHubRun>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutoHubRun>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutoHubRun>>,
          TError,
          Awaited<ReturnType<typeof getAutoHubRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutoHubRun<TData = Awaited<ReturnType<typeof getAutoHubRun>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutoHubRun>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAutoHubRun>>,
          TError,
          Awaited<ReturnType<typeof getAutoHubRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAutoHubRun<TData = Awaited<ReturnType<typeof getAutoHubRun>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutoHubRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read one Auto Hub run
 */

export function useGetAutoHubRun<TData = Awaited<ReturnType<typeof getAutoHubRun>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAutoHubRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAutoHubRunQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Real trades and shadow entries in one timeline, newest first. A shadow entry was scored against the market and never bought: it has no stake, no profit and no contract id.

 * @summary List the entries an Auto Hub run took
 */
export const listAutoHubRunEntries = (
    id: string,
    params?: ListAutoHubRunEntriesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListAutoHubRunEntries200>(
      {url: `/api/v1/autohub/runs/${id}/entries`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListAutoHubRunEntriesQueryKey = (id?: string,
    params?: ListAutoHubRunEntriesParams,) => {
    return [
    `/api/v1/autohub/runs/${id}/entries`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListAutoHubRunEntriesQueryOptions = <TData = Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError = ErrorType<void>>(id: string,
    params?: ListAutoHubRunEntriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAutoHubRunEntriesQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAutoHubRunEntries>>> = ({ signal }) => listAutoHubRunEntries(id,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAutoHubRunEntriesQueryResult = NonNullable<Awaited<ReturnType<typeof listAutoHubRunEntries>>>
export type ListAutoHubRunEntriesQueryError = ErrorType<void>


export function useListAutoHubRunEntries<TData = Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError = ErrorType<void>>(
 id: string,
    params: undefined |  ListAutoHubRunEntriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutoHubRunEntries>>,
          TError,
          Awaited<ReturnType<typeof listAutoHubRunEntries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutoHubRunEntries<TData = Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError = ErrorType<void>>(
 id: string,
    params?: ListAutoHubRunEntriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAutoHubRunEntries>>,
          TError,
          Awaited<ReturnType<typeof listAutoHubRunEntries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAutoHubRunEntries<TData = Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError = ErrorType<void>>(
 id: string,
    params?: ListAutoHubRunEntriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the entries an Auto Hub run took
 */

export function useListAutoHubRunEntries<TData = Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError = ErrorType<void>>(
 id: string,
    params?: ListAutoHubRunEntriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAutoHubRunEntries>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAutoHubRunEntriesQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * A request, not a kill. A claimed run enters `stopping` and ends once its open trade has settled; an unclaimed one completes immediately. Stopping an already-stopping run succeeds.

 * @summary Stop an Auto Hub run
 */
export const stopAutoHubRun = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AutoHubRun>(
      {url: `/api/v1/autohub/runs/${id}/stop`, method: 'POST', signal
    },
      options);
    }
  


export const getStopAutoHubRunMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopAutoHubRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stopAutoHubRun>>, TError,{id: string}, TContext> => {

const mutationKey = ['stopAutoHubRun'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stopAutoHubRun>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  stopAutoHubRun(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StopAutoHubRunMutationResult = NonNullable<Awaited<ReturnType<typeof stopAutoHubRun>>>
    
    export type StopAutoHubRunMutationError = ErrorType<void>

    /**
 * @summary Stop an Auto Hub run
 */
export const useStopAutoHubRun = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopAutoHubRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stopAutoHubRun>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getStopAutoHubRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Ends the run in whatever state it is in, so it places no further trades. An open contract is sold when Deriv will buy it back; a one-tick contract cannot be and is left to finish. Idempotent once the run has ended.

 * @summary Emergency stop an Auto Hub run
 */
export const forceStopAutoHubRun = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AutoHubRun>(
      {url: `/api/v1/autohub/runs/${id}/force-stop`, method: 'POST', signal
    },
      options);
    }
  


export const getForceStopAutoHubRunMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forceStopAutoHubRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof forceStopAutoHubRun>>, TError,{id: string}, TContext> => {

const mutationKey = ['forceStopAutoHubRun'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof forceStopAutoHubRun>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  forceStopAutoHubRun(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ForceStopAutoHubRunMutationResult = NonNullable<Awaited<ReturnType<typeof forceStopAutoHubRun>>>
    
    export type ForceStopAutoHubRunMutationError = ErrorType<void>

    /**
 * @summary Emergency stop an Auto Hub run
 */
export const useForceStopAutoHubRun = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forceStopAutoHubRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof forceStopAutoHubRun>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getForceStopAutoHubRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    