/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BotLimits,
  BotPackageFile,
  BotPackageList,
  BotPreset,
  BotPresetList,
  BotRun,
  ClaimBotPackageRequest,
  ClaimBotPackageResponse,
  CreateBotPackageRequest,
  CreateBotPackageResponse,
  CreateBotPresetRequest,
  DeleteBotPreset200,
  Error,
  ListBotPresetsParams,
  ListBotRunTrades200,
  ListBotRunTradesParams,
  ListBotRuns200,
  ListBotRunsParams,
  ListBotStrategies200,
  NotFoundResponse,
  RevokeBotPackage200,
  StartBotRunRequest,
  StartBotRunResponse,
  UnauthorizedResponse,
  UpdateBotPresetRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType , BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Save a named bot configuration
 */
export const createBotPreset = (
    createBotPresetRequest: BodyType<CreateBotPresetRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotPreset>(
      {url: `/api/v1/bots/presets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBotPresetRequest, signal
    },
      options);
    }
  


export const getCreateBotPresetMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBotPreset>>, TError,{data: BodyType<CreateBotPresetRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createBotPreset>>, TError,{data: BodyType<CreateBotPresetRequest>}, TContext> => {

const mutationKey = ['createBotPreset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBotPreset>>, {data: BodyType<CreateBotPresetRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createBotPreset(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBotPresetMutationResult = NonNullable<Awaited<ReturnType<typeof createBotPreset>>>
    export type CreateBotPresetMutationBody = BodyType<CreateBotPresetRequest>
    export type CreateBotPresetMutationError = ErrorType<Error | UnauthorizedResponse>

    /**
 * @summary Save a named bot configuration
 */
export const useCreateBotPreset = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBotPreset>>, TError,{data: BodyType<CreateBotPresetRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBotPreset>>,
        TError,
        {data: BodyType<CreateBotPresetRequest>},
        TContext
      > => {

      const mutationOptions = getCreateBotPresetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List the caller's saved presets
 */
export const listBotPresets = (
    params?: ListBotPresetsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotPresetList>(
      {url: `/api/v1/bots/presets`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListBotPresetsQueryKey = (params?: ListBotPresetsParams,) => {
    return [
    `/api/v1/bots/presets`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListBotPresetsQueryOptions = <TData = Awaited<ReturnType<typeof listBotPresets>>, TError = ErrorType<UnauthorizedResponse>>(params?: ListBotPresetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotPresets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBotPresetsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBotPresets>>> = ({ signal }) => listBotPresets(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBotPresets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListBotPresetsQueryResult = NonNullable<Awaited<ReturnType<typeof listBotPresets>>>
export type ListBotPresetsQueryError = ErrorType<UnauthorizedResponse>


export function useListBotPresets<TData = Awaited<ReturnType<typeof listBotPresets>>, TError = ErrorType<UnauthorizedResponse>>(
 params: undefined |  ListBotPresetsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotPresets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBotPresets>>,
          TError,
          Awaited<ReturnType<typeof listBotPresets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBotPresets<TData = Awaited<ReturnType<typeof listBotPresets>>, TError = ErrorType<UnauthorizedResponse>>(
 params?: ListBotPresetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotPresets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBotPresets>>,
          TError,
          Awaited<ReturnType<typeof listBotPresets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBotPresets<TData = Awaited<ReturnType<typeof listBotPresets>>, TError = ErrorType<UnauthorizedResponse>>(
 params?: ListBotPresetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotPresets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the caller's saved presets
 */

export function useListBotPresets<TData = Awaited<ReturnType<typeof listBotPresets>>, TError = ErrorType<UnauthorizedResponse>>(
 params?: ListBotPresetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotPresets>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListBotPresetsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns 404 rather than 403 for a preset belonging to another user, so the endpoint cannot be used to enumerate ids.
 * @summary Get one preset
 */
export const getBotPreset = (
    presetId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotPreset>(
      {url: `/api/v1/bots/presets/${presetId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBotPresetQueryKey = (presetId?: string,) => {
    return [
    `/api/v1/bots/presets/${presetId}`
    ] as const;
    }

    
export const getGetBotPresetQueryOptions = <TData = Awaited<ReturnType<typeof getBotPreset>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(presetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotPreset>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBotPresetQueryKey(presetId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBotPreset>>> = ({ signal }) => getBotPreset(presetId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(presetId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBotPreset>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBotPresetQueryResult = NonNullable<Awaited<ReturnType<typeof getBotPreset>>>
export type GetBotPresetQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useGetBotPreset<TData = Awaited<ReturnType<typeof getBotPreset>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 presetId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotPreset>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBotPreset>>,
          TError,
          Awaited<ReturnType<typeof getBotPreset>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBotPreset<TData = Awaited<ReturnType<typeof getBotPreset>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 presetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotPreset>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBotPreset>>,
          TError,
          Awaited<ReturnType<typeof getBotPreset>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBotPreset<TData = Awaited<ReturnType<typeof getBotPreset>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 presetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotPreset>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get one preset
 */

export function useGetBotPreset<TData = Awaited<ReturnType<typeof getBotPreset>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 presetId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotPreset>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBotPresetQueryOptions(presetId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Rename or reconfigure a preset
 */
export const updateBotPreset = (
    presetId: string,
    updateBotPresetRequest: BodyType<UpdateBotPresetRequest>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<BotPreset>(
      {url: `/api/v1/bots/presets/${presetId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateBotPresetRequest
    },
      options);
    }
  


export const getUpdateBotPresetMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBotPreset>>, TError,{presetId: string;data: BodyType<UpdateBotPresetRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBotPreset>>, TError,{presetId: string;data: BodyType<UpdateBotPresetRequest>}, TContext> => {

const mutationKey = ['updateBotPreset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBotPreset>>, {presetId: string;data: BodyType<UpdateBotPresetRequest>}> = (props) => {
          const {presetId,data} = props ?? {};

          return  updateBotPreset(presetId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateBotPresetMutationResult = NonNullable<Awaited<ReturnType<typeof updateBotPreset>>>
    export type UpdateBotPresetMutationBody = BodyType<UpdateBotPresetRequest>
    export type UpdateBotPresetMutationError = ErrorType<Error | UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Rename or reconfigure a preset
 */
export const useUpdateBotPreset = <TError = ErrorType<Error | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBotPreset>>, TError,{presetId: string;data: BodyType<UpdateBotPresetRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBotPreset>>,
        TError,
        {presetId: string;data: BodyType<UpdateBotPresetRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateBotPresetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a preset
 */
export const deleteBotPreset = (
    presetId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteBotPreset200>(
      {url: `/api/v1/bots/presets/${presetId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteBotPresetMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBotPreset>>, TError,{presetId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBotPreset>>, TError,{presetId: string}, TContext> => {

const mutationKey = ['deleteBotPreset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBotPreset>>, {presetId: string}> = (props) => {
          const {presetId} = props ?? {};

          return  deleteBotPreset(presetId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteBotPresetMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBotPreset>>>
    
    export type DeleteBotPresetMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Delete a preset
 */
export const useDeleteBotPreset = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBotPreset>>, TError,{presetId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBotPreset>>,
        TError,
        {presetId: string},
        TContext
      > => {

      const mutationOptions = getDeleteBotPresetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * The configuration is encrypted with a key derived from `password`. The password is never stored in recoverable form — losing it means losing the package.
 * @summary Export a bot as a password-protected, one-time licensed package
 */
export const createBotPackage = (
    createBotPackageRequest: BodyType<CreateBotPackageRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateBotPackageResponse>(
      {url: `/api/v1/bots/packages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBotPackageRequest, signal
    },
      options);
    }
  


export const getCreateBotPackageMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBotPackage>>, TError,{data: BodyType<CreateBotPackageRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createBotPackage>>, TError,{data: BodyType<CreateBotPackageRequest>}, TContext> => {

const mutationKey = ['createBotPackage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBotPackage>>, {data: BodyType<CreateBotPackageRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createBotPackage(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBotPackageMutationResult = NonNullable<Awaited<ReturnType<typeof createBotPackage>>>
    export type CreateBotPackageMutationBody = BodyType<CreateBotPackageRequest>
    export type CreateBotPackageMutationError = ErrorType<Error | UnauthorizedResponse>

    /**
 * @summary Export a bot as a password-protected, one-time licensed package
 */
export const useCreateBotPackage = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBotPackage>>, TError,{data: BodyType<CreateBotPackageRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBotPackage>>,
        TError,
        {data: BodyType<CreateBotPackageRequest>},
        TContext
      > => {

      const mutationOptions = getCreateBotPackageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List packages the caller created
 */
export const listMyBotPackages = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotPackageList>(
      {url: `/api/v1/bots/packages/mine`, method: 'GET', signal
    },
      options);
    }
  



export const getListMyBotPackagesQueryKey = () => {
    return [
    `/api/v1/bots/packages/mine`
    ] as const;
    }

    
export const getListMyBotPackagesQueryOptions = <TData = Awaited<ReturnType<typeof listMyBotPackages>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyBotPackages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMyBotPackagesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyBotPackages>>> = ({ signal }) => listMyBotPackages(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyBotPackages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMyBotPackagesQueryResult = NonNullable<Awaited<ReturnType<typeof listMyBotPackages>>>
export type ListMyBotPackagesQueryError = ErrorType<UnauthorizedResponse>


export function useListMyBotPackages<TData = Awaited<ReturnType<typeof listMyBotPackages>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyBotPackages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyBotPackages>>,
          TError,
          Awaited<ReturnType<typeof listMyBotPackages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyBotPackages<TData = Awaited<ReturnType<typeof listMyBotPackages>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyBotPackages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyBotPackages>>,
          TError,
          Awaited<ReturnType<typeof listMyBotPackages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyBotPackages<TData = Awaited<ReturnType<typeof listMyBotPackages>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyBotPackages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List packages the caller created
 */

export function useListMyBotPackages<TData = Awaited<ReturnType<typeof listMyBotPackages>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyBotPackages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMyBotPackagesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Supply either `package_id` or the exported `file_content`, plus the password. A package can be claimed once; a second attempt fails.
 * @summary Claim a package and unlock its configuration
 */
export const claimBotPackage = (
    claimBotPackageRequest: BodyType<ClaimBotPackageRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ClaimBotPackageResponse>(
      {url: `/api/v1/bots/packages/claim`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: claimBotPackageRequest, signal
    },
      options);
    }
  


export const getClaimBotPackageMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimBotPackage>>, TError,{data: BodyType<ClaimBotPackageRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof claimBotPackage>>, TError,{data: BodyType<ClaimBotPackageRequest>}, TContext> => {

const mutationKey = ['claimBotPackage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimBotPackage>>, {data: BodyType<ClaimBotPackageRequest>}> = (props) => {
          const {data} = props ?? {};

          return  claimBotPackage(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ClaimBotPackageMutationResult = NonNullable<Awaited<ReturnType<typeof claimBotPackage>>>
    export type ClaimBotPackageMutationBody = BodyType<ClaimBotPackageRequest>
    export type ClaimBotPackageMutationError = ErrorType<Error | UnauthorizedResponse | NotFoundResponse>

    /**
 * @summary Claim a package and unlock its configuration
 */
export const useClaimBotPackage = <TError = ErrorType<Error | UnauthorizedResponse | NotFoundResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimBotPackage>>, TError,{data: BodyType<ClaimBotPackageRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof claimBotPackage>>,
        TError,
        {data: BodyType<ClaimBotPackageRequest>},
        TContext
      > => {

      const mutationOptions = getClaimBotPackageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Download the armoured package file
 */
export const downloadBotPackage = (
    packageId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotPackageFile>(
      {url: `/api/v1/bots/packages/${packageId}/download`, method: 'GET', signal
    },
      options);
    }
  



export const getDownloadBotPackageQueryKey = (packageId?: string,) => {
    return [
    `/api/v1/bots/packages/${packageId}/download`
    ] as const;
    }

    
export const getDownloadBotPackageQueryOptions = <TData = Awaited<ReturnType<typeof downloadBotPackage>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(packageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadBotPackage>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadBotPackageQueryKey(packageId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadBotPackage>>> = ({ signal }) => downloadBotPackage(packageId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(packageId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadBotPackage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadBotPackageQueryResult = NonNullable<Awaited<ReturnType<typeof downloadBotPackage>>>
export type DownloadBotPackageQueryError = ErrorType<UnauthorizedResponse | NotFoundResponse>


export function useDownloadBotPackage<TData = Awaited<ReturnType<typeof downloadBotPackage>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 packageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadBotPackage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadBotPackage>>,
          TError,
          Awaited<ReturnType<typeof downloadBotPackage>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadBotPackage<TData = Awaited<ReturnType<typeof downloadBotPackage>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 packageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadBotPackage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadBotPackage>>,
          TError,
          Awaited<ReturnType<typeof downloadBotPackage>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadBotPackage<TData = Awaited<ReturnType<typeof downloadBotPackage>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 packageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadBotPackage>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download the armoured package file
 */

export function useDownloadBotPackage<TData = Awaited<ReturnType<typeof downloadBotPackage>>, TError = ErrorType<UnauthorizedResponse | NotFoundResponse>>(
 packageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadBotPackage>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadBotPackageQueryOptions(packageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Revoke an unclaimed package
 */
export const revokeBotPackage = (
    packageId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<RevokeBotPackage200>(
      {url: `/api/v1/bots/packages/${packageId}`, method: 'DELETE'
    },
      options);
    }
  


export const getRevokeBotPackageMutationOptions = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse | Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeBotPackage>>, TError,{packageId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeBotPackage>>, TError,{packageId: string}, TContext> => {

const mutationKey = ['revokeBotPackage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeBotPackage>>, {packageId: string}> = (props) => {
          const {packageId} = props ?? {};

          return  revokeBotPackage(packageId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeBotPackageMutationResult = NonNullable<Awaited<ReturnType<typeof revokeBotPackage>>>
    
    export type RevokeBotPackageMutationError = ErrorType<UnauthorizedResponse | NotFoundResponse | Error>

    /**
 * @summary Revoke an unclaimed package
 */
export const useRevokeBotPackage = <TError = ErrorType<UnauthorizedResponse | NotFoundResponse | Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeBotPackage>>, TError,{packageId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeBotPackage>>,
        TError,
        {packageId: string},
        TContext
      > => {

      const mutationOptions = getRevokeBotPackageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Each bot carries a JSON Schema describing its own parameters. The frontend renders the configuration form from that schema, so adding a bot does not require a new settings screen.

 * @summary List available bots
 */
export const listBotStrategies = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListBotStrategies200>(
      {url: `/api/v1/bots/strategies`, method: 'GET', signal
    },
      options);
    }
  



export const getListBotStrategiesQueryKey = () => {
    return [
    `/api/v1/bots/strategies`
    ] as const;
    }

    
export const getListBotStrategiesQueryOptions = <TData = Awaited<ReturnType<typeof listBotStrategies>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotStrategies>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBotStrategiesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBotStrategies>>> = ({ signal }) => listBotStrategies(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBotStrategies>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListBotStrategiesQueryResult = NonNullable<Awaited<ReturnType<typeof listBotStrategies>>>
export type ListBotStrategiesQueryError = ErrorType<unknown>


export function useListBotStrategies<TData = Awaited<ReturnType<typeof listBotStrategies>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotStrategies>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBotStrategies>>,
          TError,
          Awaited<ReturnType<typeof listBotStrategies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBotStrategies<TData = Awaited<ReturnType<typeof listBotStrategies>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotStrategies>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBotStrategies>>,
          TError,
          Awaited<ReturnType<typeof listBotStrategies>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBotStrategies<TData = Awaited<ReturnType<typeof listBotStrategies>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotStrategies>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List available bots
 */

export function useListBotStrategies<TData = Awaited<ReturnType<typeof listBotStrategies>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotStrategies>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListBotStrategiesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * The maximum a user may configure. Exposed so the UI can show the cap before a larger number is entered and silently clamped.

 * @summary Platform-wide risk ceilings
 */
export const getBotLimits = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotLimits>(
      {url: `/api/v1/bots/limits`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBotLimitsQueryKey = () => {
    return [
    `/api/v1/bots/limits`
    ] as const;
    }

    
export const getGetBotLimitsQueryOptions = <TData = Awaited<ReturnType<typeof getBotLimits>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotLimits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBotLimitsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBotLimits>>> = ({ signal }) => getBotLimits(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBotLimits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBotLimitsQueryResult = NonNullable<Awaited<ReturnType<typeof getBotLimits>>>
export type GetBotLimitsQueryError = ErrorType<unknown>


export function useGetBotLimits<TData = Awaited<ReturnType<typeof getBotLimits>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotLimits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBotLimits>>,
          TError,
          Awaited<ReturnType<typeof getBotLimits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBotLimits<TData = Awaited<ReturnType<typeof getBotLimits>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotLimits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBotLimits>>,
          TError,
          Awaited<ReturnType<typeof getBotLimits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBotLimits<TData = Awaited<ReturnType<typeof getBotLimits>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotLimits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Platform-wide risk ceilings
 */

export function useGetBotLimits<TData = Awaited<ReturnType<typeof getBotLimits>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotLimits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBotLimitsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List this user's bot runs
 */
export const listBotRuns = (
    params?: ListBotRunsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListBotRuns200>(
      {url: `/api/v1/bots/runs`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListBotRunsQueryKey = (params?: ListBotRunsParams,) => {
    return [
    `/api/v1/bots/runs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListBotRunsQueryOptions = <TData = Awaited<ReturnType<typeof listBotRuns>>, TError = ErrorType<unknown>>(params?: ListBotRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRuns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBotRunsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBotRuns>>> = ({ signal }) => listBotRuns(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBotRuns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListBotRunsQueryResult = NonNullable<Awaited<ReturnType<typeof listBotRuns>>>
export type ListBotRunsQueryError = ErrorType<unknown>


export function useListBotRuns<TData = Awaited<ReturnType<typeof listBotRuns>>, TError = ErrorType<unknown>>(
 params: undefined |  ListBotRunsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRuns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBotRuns>>,
          TError,
          Awaited<ReturnType<typeof listBotRuns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBotRuns<TData = Awaited<ReturnType<typeof listBotRuns>>, TError = ErrorType<unknown>>(
 params?: ListBotRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRuns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBotRuns>>,
          TError,
          Awaited<ReturnType<typeof listBotRuns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBotRuns<TData = Awaited<ReturnType<typeof listBotRuns>>, TError = ErrorType<unknown>>(
 params?: ListBotRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRuns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List this user's bot runs
 */

export function useListBotRuns<TData = Awaited<ReturnType<typeof listBotRuns>>, TError = ErrorType<unknown>>(
 params?: ListBotRunsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRuns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListBotRunsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Validates and queues a run. Over-cap risk limits are CLAMPED rather than rejected, and the reductions are returned in `limit_adjustments` — the caller must surface them, because the user would otherwise believe the number they typed was honoured.

A session stop loss is mandatory: there is no representation of a run without one, because a bot with no loss bound can empty an account while the user is asleep.

 * @summary Start a bot run
 */
export const startBotRun = (
    startBotRunRequest: BodyType<StartBotRunRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StartBotRunResponse>(
      {url: `/api/v1/bots/runs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startBotRunRequest, signal
    },
      options);
    }
  


export const getStartBotRunMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startBotRun>>, TError,{data: BodyType<StartBotRunRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startBotRun>>, TError,{data: BodyType<StartBotRunRequest>}, TContext> => {

const mutationKey = ['startBotRun'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startBotRun>>, {data: BodyType<StartBotRunRequest>}> = (props) => {
          const {data} = props ?? {};

          return  startBotRun(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StartBotRunMutationResult = NonNullable<Awaited<ReturnType<typeof startBotRun>>>
    export type StartBotRunMutationBody = BodyType<StartBotRunRequest>
    export type StartBotRunMutationError = ErrorType<void>

    /**
 * @summary Start a bot run
 */
export const useStartBotRun = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startBotRun>>, TError,{data: BodyType<StartBotRunRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startBotRun>>,
        TError,
        {data: BodyType<StartBotRunRequest>},
        TContext
      > => {

      const mutationOptions = getStartBotRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Read one bot run
 */
export const getBotRun = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotRun>(
      {url: `/api/v1/bots/runs/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBotRunQueryKey = (id?: string,) => {
    return [
    `/api/v1/bots/runs/${id}`
    ] as const;
    }

    
export const getGetBotRunQueryOptions = <TData = Awaited<ReturnType<typeof getBotRun>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBotRunQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBotRun>>> = ({ signal }) => getBotRun(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBotRun>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBotRunQueryResult = NonNullable<Awaited<ReturnType<typeof getBotRun>>>
export type GetBotRunQueryError = ErrorType<void>


export function useGetBotRun<TData = Awaited<ReturnType<typeof getBotRun>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotRun>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBotRun>>,
          TError,
          Awaited<ReturnType<typeof getBotRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBotRun<TData = Awaited<ReturnType<typeof getBotRun>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotRun>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBotRun>>,
          TError,
          Awaited<ReturnType<typeof getBotRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBotRun<TData = Awaited<ReturnType<typeof getBotRun>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read one bot run
 */

export function useGetBotRun<TData = Awaited<ReturnType<typeof getBotRun>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBotRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBotRunQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Newest first. The `summary` covers the WHOLE run, not the requested page — a win rate computed over one page would be actively misleading.

`profit_loss` and `outcome` are absent while a contract is still open. Reporting a profit of 0 for an unsettled contract would read as break-even, which is a different claim from "not yet known".

 * @summary List the trades a bot run has placed
 */
export const listBotRunTrades = (
    id: string,
    params?: ListBotRunTradesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListBotRunTrades200>(
      {url: `/api/v1/bots/runs/${id}/trades`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListBotRunTradesQueryKey = (id?: string,
    params?: ListBotRunTradesParams,) => {
    return [
    `/api/v1/bots/runs/${id}/trades`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListBotRunTradesQueryOptions = <TData = Awaited<ReturnType<typeof listBotRunTrades>>, TError = ErrorType<void>>(id: string,
    params?: ListBotRunTradesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRunTrades>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBotRunTradesQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBotRunTrades>>> = ({ signal }) => listBotRunTrades(id,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBotRunTrades>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListBotRunTradesQueryResult = NonNullable<Awaited<ReturnType<typeof listBotRunTrades>>>
export type ListBotRunTradesQueryError = ErrorType<void>


export function useListBotRunTrades<TData = Awaited<ReturnType<typeof listBotRunTrades>>, TError = ErrorType<void>>(
 id: string,
    params: undefined |  ListBotRunTradesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRunTrades>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBotRunTrades>>,
          TError,
          Awaited<ReturnType<typeof listBotRunTrades>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBotRunTrades<TData = Awaited<ReturnType<typeof listBotRunTrades>>, TError = ErrorType<void>>(
 id: string,
    params?: ListBotRunTradesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRunTrades>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBotRunTrades>>,
          TError,
          Awaited<ReturnType<typeof listBotRunTrades>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBotRunTrades<TData = Awaited<ReturnType<typeof listBotRunTrades>>, TError = ErrorType<void>>(
 id: string,
    params?: ListBotRunTradesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRunTrades>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the trades a bot run has placed
 */

export function useListBotRunTrades<TData = Awaited<ReturnType<typeof listBotRunTrades>>, TError = ErrorType<void>>(
 id: string,
    params?: ListBotRunTradesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBotRunTrades>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListBotRunTradesQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * A request, not a kill. A claimed run enters `stopping` so the worker can wind down open contracts; an unclaimed one completes immediately. Idempotent — stopping an already-stopping run succeeds.

 * @summary Stop a bot run
 */
export const stopBotRun = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotRun>(
      {url: `/api/v1/bots/runs/${id}/stop`, method: 'POST', signal
    },
      options);
    }
  


export const getStopBotRunMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopBotRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stopBotRun>>, TError,{id: string}, TContext> => {

const mutationKey = ['stopBotRun'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stopBotRun>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  stopBotRun(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StopBotRunMutationResult = NonNullable<Awaited<ReturnType<typeof stopBotRun>>>
    
    export type StopBotRunMutationError = ErrorType<void>

    /**
 * @summary Stop a bot run
 */
export const useStopBotRun = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stopBotRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stopBotRun>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getStopBotRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Stops new orders. Open contracts are left to settle — closing them early would realise losses the user never asked to realise.

 * @summary Pause a bot run
 */
export const pauseBotRun = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotRun>(
      {url: `/api/v1/bots/runs/${id}/pause`, method: 'POST', signal
    },
      options);
    }
  


export const getPauseBotRunMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseBotRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof pauseBotRun>>, TError,{id: string}, TContext> => {

const mutationKey = ['pauseBotRun'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pauseBotRun>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  pauseBotRun(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PauseBotRunMutationResult = NonNullable<Awaited<ReturnType<typeof pauseBotRun>>>
    
    export type PauseBotRunMutationError = ErrorType<void>

    /**
 * @summary Pause a bot run
 */
export const usePauseBotRun = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseBotRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pauseBotRun>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPauseBotRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Resume a paused bot run
 */
export const resumeBotRun = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotRun>(
      {url: `/api/v1/bots/runs/${id}/resume`, method: 'POST', signal
    },
      options);
    }
  


export const getResumeBotRunMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeBotRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resumeBotRun>>, TError,{id: string}, TContext> => {

const mutationKey = ['resumeBotRun'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resumeBotRun>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  resumeBotRun(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResumeBotRunMutationResult = NonNullable<Awaited<ReturnType<typeof resumeBotRun>>>
    
    export type ResumeBotRunMutationError = ErrorType<void>

    /**
 * @summary Resume a paused bot run
 */
export const useResumeBotRun = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeBotRun>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resumeBotRun>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getResumeBotRunMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    