/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision â€” parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List all blogs
 */
export const getApiV1AdminBlogs = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/admin/blogs`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1AdminBlogsQueryKey = () => {
    return [
    `/api/v1/admin/blogs`
    ] as const;
    }

    
export const getGetApiV1AdminBlogsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminBlogsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminBlogs>>> = ({ signal }) => getApiV1AdminBlogs(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminBlogsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminBlogs>>>
export type GetApiV1AdminBlogsQueryError = ErrorType<unknown>


export function useGetApiV1AdminBlogs<TData = Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminBlogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminBlogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminBlogs<TData = Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminBlogs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminBlogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminBlogs<TData = Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all blogs
 */

export function useGetApiV1AdminBlogs<TData = Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminBlogsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create a blog
 */
export const postApiV1AdminBlogs = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/admin/blogs`, method: 'POST', signal
    },
      options);
    }
  


export const getPostApiV1AdminBlogsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminBlogs>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminBlogs>>, TError,void, TContext> => {

const mutationKey = ['postApiV1AdminBlogs'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AdminBlogs>>, void> = () => {
          

          return  postApiV1AdminBlogs(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AdminBlogsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AdminBlogs>>>
    
    export type PostApiV1AdminBlogsMutationError = ErrorType<unknown>

    /**
 * @summary Create a blog
 */
export const usePostApiV1AdminBlogs = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AdminBlogs>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AdminBlogs>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiV1AdminBlogsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get blog by id
 */
export const getApiV1AdminBlogsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/admin/blogs/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1AdminBlogsIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/admin/blogs/${id}`
    ] as const;
    }

    
export const getGetApiV1AdminBlogsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AdminBlogsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AdminBlogsId>>> = ({ signal }) => getApiV1AdminBlogsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AdminBlogsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AdminBlogsId>>>
export type GetApiV1AdminBlogsIdQueryError = ErrorType<unknown>


export function useGetApiV1AdminBlogsId<TData = Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminBlogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminBlogsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminBlogsId<TData = Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AdminBlogsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AdminBlogsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AdminBlogsId<TData = Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get blog by id
 */

export function useGetApiV1AdminBlogsId<TData = Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AdminBlogsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AdminBlogsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update a blog
 */
export const putApiV1AdminBlogsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/admin/blogs/${id}`, method: 'PUT'
    },
      options);
    }
  


export const getPutApiV1AdminBlogsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminBlogsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminBlogsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['putApiV1AdminBlogsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1AdminBlogsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  putApiV1AdminBlogsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1AdminBlogsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1AdminBlogsId>>>
    
    export type PutApiV1AdminBlogsIdMutationError = ErrorType<unknown>

    /**
 * @summary Update a blog
 */
export const usePutApiV1AdminBlogsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1AdminBlogsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1AdminBlogsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPutApiV1AdminBlogsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete a blog
 */
export const deleteApiV1AdminBlogsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/admin/blogs/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV1AdminBlogsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminBlogsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminBlogsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV1AdminBlogsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1AdminBlogsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV1AdminBlogsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV1AdminBlogsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AdminBlogsId>>>
    
    export type DeleteApiV1AdminBlogsIdMutationError = ErrorType<unknown>

    /**
 * @summary Delete a blog
 */
export const useDeleteApiV1AdminBlogsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AdminBlogsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV1AdminBlogsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV1AdminBlogsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Toggle blog visibility
 */
export const patchApiV1AdminBlogsIdVisibility = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/admin/blogs/${id}/visibility`, method: 'PATCH'
    },
      options);
    }
  


export const getPatchApiV1AdminBlogsIdVisibilityMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AdminBlogsIdVisibility>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AdminBlogsIdVisibility>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiV1AdminBlogsIdVisibility'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiV1AdminBlogsIdVisibility>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiV1AdminBlogsIdVisibility(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiV1AdminBlogsIdVisibilityMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiV1AdminBlogsIdVisibility>>>
    
    export type PatchApiV1AdminBlogsIdVisibilityMutationError = ErrorType<unknown>

    /**
 * @summary Toggle blog visibility
 */
export const usePatchApiV1AdminBlogsIdVisibility = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiV1AdminBlogsIdVisibility>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiV1AdminBlogsIdVisibility>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPatchApiV1AdminBlogsIdVisibilityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    