/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision â€” parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommissionHistoryResponse,
  GetCommissionHistoryParams,
  UnauthorizedResponse,
  ValidationErrorResponse
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Commission ledger history
 */
export const getCommissionHistory = (
    params?: GetCommissionHistoryParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CommissionHistoryResponse>(
      {url: `/api/v1/commissions/history`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCommissionHistoryQueryKey = (params?: GetCommissionHistoryParams,) => {
    return [
    `/api/v1/commissions/history`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCommissionHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getCommissionHistory>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(params?: GetCommissionHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCommissionHistoryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommissionHistory>>> = ({ signal }) => getCommissionHistory(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCommissionHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCommissionHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getCommissionHistory>>>
export type GetCommissionHistoryQueryError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>


export function useGetCommissionHistory<TData = Awaited<ReturnType<typeof getCommissionHistory>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params: undefined |  GetCommissionHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommissionHistory>>,
          TError,
          Awaited<ReturnType<typeof getCommissionHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommissionHistory<TData = Awaited<ReturnType<typeof getCommissionHistory>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params?: GetCommissionHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommissionHistory>>,
          TError,
          Awaited<ReturnType<typeof getCommissionHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommissionHistory<TData = Awaited<ReturnType<typeof getCommissionHistory>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params?: GetCommissionHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Commission ledger history
 */

export function useGetCommissionHistory<TData = Awaited<ReturnType<typeof getCommissionHistory>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params?: GetCommissionHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommissionHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCommissionHistoryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




