/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthorizeResponse,
  ConfirmRequest,
  ConfirmResponse,
  DerivAccountStatus,
  DerivLinkRequest,
  DerivLinkResponse,
  DerivUnlink200,
  Error,
  ProposalRequest,
  ProposalResponse,
  TradeHistoryEntry,
  UnauthorizedResponse
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType , BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Build the Deriv OAuth authorize URL
 */
export const derivAuthorize = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthorizeResponse>(
      {url: `/api/v1/deriv/oauth/authorize`, method: 'GET', signal
    },
      options);
    }
  



export const getDerivAuthorizeQueryKey = () => {
    return [
    `/api/v1/deriv/oauth/authorize`
    ] as const;
    }

    
export const getDerivAuthorizeQueryOptions = <TData = Awaited<ReturnType<typeof derivAuthorize>>, TError = ErrorType<UnauthorizedResponse | Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAuthorize>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDerivAuthorizeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof derivAuthorize>>> = ({ signal }) => derivAuthorize(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof derivAuthorize>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DerivAuthorizeQueryResult = NonNullable<Awaited<ReturnType<typeof derivAuthorize>>>
export type DerivAuthorizeQueryError = ErrorType<UnauthorizedResponse | Error>


export function useDerivAuthorize<TData = Awaited<ReturnType<typeof derivAuthorize>>, TError = ErrorType<UnauthorizedResponse | Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAuthorize>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof derivAuthorize>>,
          TError,
          Awaited<ReturnType<typeof derivAuthorize>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDerivAuthorize<TData = Awaited<ReturnType<typeof derivAuthorize>>, TError = ErrorType<UnauthorizedResponse | Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAuthorize>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof derivAuthorize>>,
          TError,
          Awaited<ReturnType<typeof derivAuthorize>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDerivAuthorize<TData = Awaited<ReturnType<typeof derivAuthorize>>, TError = ErrorType<UnauthorizedResponse | Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAuthorize>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Build the Deriv OAuth authorize URL
 */

export function useDerivAuthorize<TData = Awaited<ReturnType<typeof derivAuthorize>>, TError = ErrorType<UnauthorizedResponse | Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAuthorize>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDerivAuthorizeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Stores the encrypted Deriv OAuth token for the chosen account.
 * @summary Link a Deriv account
 */
export const derivLink = (
    derivLinkRequest: BodyType<DerivLinkRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DerivLinkResponse>(
      {url: `/api/v1/deriv/oauth/link`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: derivLinkRequest, signal
    },
      options);
    }
  


export const getDerivLinkMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof derivLink>>, TError,{data: BodyType<DerivLinkRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof derivLink>>, TError,{data: BodyType<DerivLinkRequest>}, TContext> => {

const mutationKey = ['derivLink'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof derivLink>>, {data: BodyType<DerivLinkRequest>}> = (props) => {
          const {data} = props ?? {};

          return  derivLink(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DerivLinkMutationResult = NonNullable<Awaited<ReturnType<typeof derivLink>>>
    export type DerivLinkMutationBody = BodyType<DerivLinkRequest>
    export type DerivLinkMutationError = ErrorType<Error | UnauthorizedResponse>

    /**
 * @summary Link a Deriv account
 */
export const useDerivLink = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof derivLink>>, TError,{data: BodyType<DerivLinkRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof derivLink>>,
        TError,
        {data: BodyType<DerivLinkRequest>},
        TContext
      > => {

      const mutationOptions = getDerivLinkMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Linked Deriv account status
 */
export const derivAccountStatus = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DerivAccountStatus>(
      {url: `/api/v1/deriv/account/status`, method: 'GET', signal
    },
      options);
    }
  



export const getDerivAccountStatusQueryKey = () => {
    return [
    `/api/v1/deriv/account/status`
    ] as const;
    }

    
export const getDerivAccountStatusQueryOptions = <TData = Awaited<ReturnType<typeof derivAccountStatus>>, TError = ErrorType<UnauthorizedResponse | Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAccountStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDerivAccountStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof derivAccountStatus>>> = ({ signal }) => derivAccountStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof derivAccountStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DerivAccountStatusQueryResult = NonNullable<Awaited<ReturnType<typeof derivAccountStatus>>>
export type DerivAccountStatusQueryError = ErrorType<UnauthorizedResponse | Error>


export function useDerivAccountStatus<TData = Awaited<ReturnType<typeof derivAccountStatus>>, TError = ErrorType<UnauthorizedResponse | Error>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAccountStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof derivAccountStatus>>,
          TError,
          Awaited<ReturnType<typeof derivAccountStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDerivAccountStatus<TData = Awaited<ReturnType<typeof derivAccountStatus>>, TError = ErrorType<UnauthorizedResponse | Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAccountStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof derivAccountStatus>>,
          TError,
          Awaited<ReturnType<typeof derivAccountStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDerivAccountStatus<TData = Awaited<ReturnType<typeof derivAccountStatus>>, TError = ErrorType<UnauthorizedResponse | Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAccountStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Linked Deriv account status
 */

export function useDerivAccountStatus<TData = Awaited<ReturnType<typeof derivAccountStatus>>, TError = ErrorType<UnauthorizedResponse | Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof derivAccountStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDerivAccountStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Unlink the Deriv account
 */
export const derivUnlink = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DerivUnlink200>(
      {url: `/api/v1/deriv/oauth`, method: 'DELETE'
    },
      options);
    }
  


export const getDerivUnlinkMutationOptions = <TError = ErrorType<UnauthorizedResponse | Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof derivUnlink>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof derivUnlink>>, TError,void, TContext> => {

const mutationKey = ['derivUnlink'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof derivUnlink>>, void> = () => {
          

          return  derivUnlink(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DerivUnlinkMutationResult = NonNullable<Awaited<ReturnType<typeof derivUnlink>>>
    
    export type DerivUnlinkMutationError = ErrorType<UnauthorizedResponse | Error>

    /**
 * @summary Unlink the Deriv account
 */
export const useDerivUnlink = <TError = ErrorType<UnauthorizedResponse | Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof derivUnlink>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof derivUnlink>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getDerivUnlinkMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Phase 1 of the slippage-safe order flow. Returns a short-lived
(~5s) binding quote. Optional fields are validated per contract type.

 * @summary Request a binding price quote (proposal)
 */
export const createProposal = (
    proposalRequest: BodyType<ProposalRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProposalResponse>(
      {url: `/api/v1/orders/proposal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: proposalRequest, signal
    },
      options);
    }
  


export const getCreateProposalMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProposal>>, TError,{data: BodyType<ProposalRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createProposal>>, TError,{data: BodyType<ProposalRequest>}, TContext> => {

const mutationKey = ['createProposal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProposal>>, {data: BodyType<ProposalRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createProposal(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProposalMutationResult = NonNullable<Awaited<ReturnType<typeof createProposal>>>
    export type CreateProposalMutationBody = BodyType<ProposalRequest>
    export type CreateProposalMutationError = ErrorType<Error | UnauthorizedResponse>

    /**
 * @summary Request a binding price quote (proposal)
 */
export const useCreateProposal = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProposal>>, TError,{data: BodyType<ProposalRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProposal>>,
        TError,
        {data: BodyType<ProposalRequest>},
        TContext
      > => {

      const mutationOptions = getCreateProposalMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Phase 2 of the order flow. Executes a previously-quoted proposal at the
guaranteed price and records the trade + TRADE_COMPLETED outbox event.

 * @summary Confirm and execute a proposal
 */
export const confirmProposal = (
    confirmRequest: BodyType<ConfirmRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ConfirmResponse>(
      {url: `/api/v1/orders/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confirmRequest, signal
    },
      options);
    }
  


export const getConfirmProposalMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmProposal>>, TError,{data: BodyType<ConfirmRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmProposal>>, TError,{data: BodyType<ConfirmRequest>}, TContext> => {

const mutationKey = ['confirmProposal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmProposal>>, {data: BodyType<ConfirmRequest>}> = (props) => {
          const {data} = props ?? {};

          return  confirmProposal(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmProposalMutationResult = NonNullable<Awaited<ReturnType<typeof confirmProposal>>>
    export type ConfirmProposalMutationBody = BodyType<ConfirmRequest>
    export type ConfirmProposalMutationError = ErrorType<Error | UnauthorizedResponse>

    /**
 * @summary Confirm and execute a proposal
 */
export const useConfirmProposal = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmProposal>>, TError,{data: BodyType<ConfirmRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmProposal>>,
        TError,
        {data: BodyType<ConfirmRequest>},
        TContext
      > => {

      const mutationOptions = getConfirmProposalMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Convenience endpoint that runs the proposal and buy steps back-to-back
with no confirmation window. Same request body as /orders/proposal; same
response as /orders/confirm. The buy is still capped at the freshly
quoted ask price, but there is no displayed-quote step — prefer the
two-phase /orders/proposal → /orders/confirm flow when you want to show
the user the payout before committing.

 * @summary Place a single-shot trade (proposal + immediate buy)
 */
export const placeTrade = (
    proposalRequest: BodyType<ProposalRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ConfirmResponse>(
      {url: `/api/v1/orders/trade`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: proposalRequest, signal
    },
      options);
    }
  


export const getPlaceTradeMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof placeTrade>>, TError,{data: BodyType<ProposalRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof placeTrade>>, TError,{data: BodyType<ProposalRequest>}, TContext> => {

const mutationKey = ['placeTrade'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof placeTrade>>, {data: BodyType<ProposalRequest>}> = (props) => {
          const {data} = props ?? {};

          return  placeTrade(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlaceTradeMutationResult = NonNullable<Awaited<ReturnType<typeof placeTrade>>>
    export type PlaceTradeMutationBody = BodyType<ProposalRequest>
    export type PlaceTradeMutationError = ErrorType<Error | UnauthorizedResponse>

    /**
 * @summary Place a single-shot trade (proposal + immediate buy)
 */
export const usePlaceTrade = <TError = ErrorType<Error | UnauthorizedResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof placeTrade>>, TError,{data: BodyType<ProposalRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof placeTrade>>,
        TError,
        {data: BodyType<ProposalRequest>},
        TContext
      > => {

      const mutationOptions = getPlaceTradeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get user trade history
 */
export const getTradeHistory = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TradeHistoryEntry[]>(
      {url: `/api/v1/orders/history`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTradeHistoryQueryKey = () => {
    return [
    `/api/v1/orders/history`
    ] as const;
    }

    
export const getGetTradeHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getTradeHistory>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTradeHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTradeHistoryQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTradeHistory>>> = ({ signal }) => getTradeHistory(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTradeHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTradeHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getTradeHistory>>>
export type GetTradeHistoryQueryError = ErrorType<UnauthorizedResponse>


export function useGetTradeHistory<TData = Awaited<ReturnType<typeof getTradeHistory>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTradeHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTradeHistory>>,
          TError,
          Awaited<ReturnType<typeof getTradeHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTradeHistory<TData = Awaited<ReturnType<typeof getTradeHistory>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTradeHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTradeHistory>>,
          TError,
          Awaited<ReturnType<typeof getTradeHistory>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTradeHistory<TData = Awaited<ReturnType<typeof getTradeHistory>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTradeHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user trade history
 */

export function useGetTradeHistory<TData = Awaited<ReturnType<typeof getTradeHistory>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTradeHistory>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTradeHistoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

export type SellRequestType = {
  contract_id: string;
  price?: string;
};

export type SellResponse = {
  contract_id: string;
  sold_for: string;
  balance_after: string;
  transaction_id: number;
};

export const sellPosition = (
  sellRequest: BodyType<SellRequestType>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SellResponse>(
    {
      url: `/api/v1/orders/sell`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sellRequest,
    },
    options,
  );
};

export const useSellPosition = <
  TError = ErrorType<Error | UnauthorizedResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sellPosition>>,
      TError,
      { data: BodyType<SellRequestType> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
) => {
  const mutationKey = ['sellPosition'];
  const mutationOptions = options?.mutation
    ? { ...options.mutation, mutationKey }
    : { mutationKey };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sellPosition>>,
    { data: BodyType<SellRequestType> }
  > = (props) => {
    const { data } = props ?? {};
    return sellPosition(data, options?.request);
  };

  return useMutation({ mutationFn, ...mutationOptions }, queryClient);
};
