/**
 * Synthetic indices, one family at a time, plus the two ideas a reader needs
 * to compare them: what a payout is, and how options differ from CFDs.
 *
 * How each index is built is Deriv's description, read on Deriv's synthetic
 * indices page on the date in learnDeriv.ts (`CHECKED`). Where that page is
 * silent (the size of a Boom spike, the odds of a Step going up) the guide
 * says so and does not supply a figure from elsewhere.
 */
import { RISK_NOTE, type Guide } from "./guides";
import { SOURCE_NOTE } from "./learnDeriv";

const TAG = "Synthetic indices";
const DATE = "2026-10-09";

export const SYNTHETIC_GUIDES: Guide[] = [
  {
    slug: "what-are-synthetic-indices",
    title: "What are synthetic indices?",
    description:
      "Synthetic indices are simulated markets whose prices come from a random number generator, not from buyers and sellers. The families and how they differ.",
    tag: TAG,
    published: DATE,
    updated: DATE,
    image: "/assets/login-slide-1.jpg",
    answer:
      "Synthetic indices are simulated markets created by a broker. Their prices are produced by a random number generator built to behave in a chosen way, such as a fixed level of volatility, and are not set by buyers and sellers. Deriv's synthetic indices trade around the clock and, Deriv says, are not affected by news.",
    body: [
      { type: "h2", text: "How they differ from a real market" },
      {
        type: "table",
        head: ["", "Real market", "Synthetic index"],
        rows: [
          ["Price comes from", "Trades between buyers and sellers", "A random number generator"],
          ["Order book", "Yes", "None"],
          ["Reacts to news", "Yes", "No, according to Deriv"],
          ["Hours", "Set by the market", "Round the clock, including weekends"],
          ["Available at", "Many brokers", "Only the broker that created it"],
        ],
      },
      { type: "h2", text: "The families Deriv describes" },
      {
        type: "table",
        head: ["Family", "Built to do this"],
        rows: [
          ["Volatility", "Hold a constant volatility, from 10% to 250%, ticking every two seconds or every second"],
          ["Crash and Boom", "Move steadily, with a sudden drop or surge on average once per set number of ticks"],
          ["Step", "Move up or down by a fixed amount on every tick"],
          ["Jump", "Jump on average every 20 minutes, with an equal chance of up or down"],
          ["Range Break", "Stay between two boundaries, then break out to form a new range"],
          ["DEX", "Produce large spikes or drops on average every 10, 15 or 25 minutes"],
          ["Drift Switching", "Shift between rising, falling and sideways phases"],
        ],
      },
      { type: "h2", text: "What can be traded on them" },
      {
        type: "p",
        text: "Deriv's page lists options on synthetic indices through Deriv Trader and Deriv Bot, and CFDs through Deriv MT5, Deriv cTrader and TradingView. Which products you see depends on your country and the Deriv entity your account is with.",
      },
      { type: "h2", text: "What random means for a trader" },
      {
        type: "list",
        items: [
          "Deriv states there is no order book and describes historical patterns on these indices as coincidental.",
          "The size of moves is designed and predictable. The direction of the next move is not.",
          "Indicators and chart patterns draw correctly and carry no information about the next tick.",
          "Results depend on the payout, the stake and your limits, not on forecasting.",
        ],
      },
      { type: "h2", text: "Why people trade them" },
      {
        type: "list",
        items: [
          "They are always open, so a strategy or bot can run at any hour.",
          "Behaviour is consistent: no earnings, no central banks, no weekend gaps.",
          "Small stakes and very short contracts are available.",
        ],
      },
      {
        type: "p",
        text: "The same features make it easy to place many high-risk trades quickly on a product priced by the company on the other side of the trade.",
      },
      { type: "h2", text: "In FXNOD" },
      {
        type: "p",
        text: "FXNOD's tools trade the markets your Deriv account offers. Auto Hub's fade bots suggest volatility indices, and the market picker in dTrader and dBot lists what is available to you. Try any index on the demo account first.",
      },
      SOURCE_NOTE,
      RISK_NOTE,
    ],
    faq: [
      {
        q: "Are synthetic indices real?",
        a: "They are real products you can trade and lose money on. They do not represent any real asset: the price is generated by an algorithm.",
      },
      {
        q: "Who invented synthetic indices?",
        a: "The synthetic indices described here are Deriv's own products. Other brokers offer their own simulated markets under different names.",
      },
      {
        q: "Can you predict synthetic indices?",
        a: "Not the direction. Deriv describes them as generated by a cryptographically secure random number generator and says historical patterns are coincidental.",
      },
      {
        q: "Are synthetic indices forex?",
        a: "No. Forex is the exchange of real currencies. Synthetic indices are simulations that have no link to any currency.",
      },
    ],
    related: ["forex-vs-synthetic-indices", "which-volatility-index-is-best"],
  },

  {
    slug: "volatility-75-index-explained",
    title: "Volatility 75 Index: what it is and how it behaves",
    description:
      "Volatility 75 is a Deriv synthetic index built to hold 75% volatility. What that means per tick, how it compares with other indices, and the risks.",
    tag: TAG,
    published: DATE,
    updated: DATE,
    image: "/assets/login-slide-2.jpg",
    answer:
      "The Volatility 75 Index is a synthetic index from Deriv built to hold a constant volatility of 75%. Its price comes from a random number generator, it trades around the clock, and it ticks every two seconds, or every second on the (1s) version. It is among the more volatile of the volatility indices, so prices move further per tick.",
    body: [
      { type: "h2", text: "What 75% volatility means" },
      {
        type: "p",
        text: "Volatility is quoted per year. As a rule of thumb, the typical move over a shorter period is the annual figure multiplied by the square root of that fraction of a year. For 75% that works out to roughly 4% in a day and about 0.1% in a minute. The figures are an illustration of scale from that rule, not a specification from Deriv.",
      },
      {
        type: "table",
        head: ["Index", "Designed volatility", "Typical daily move by the same rule"],
        rows: [
          ["Volatility 10", "10%", "About 0.5%"],
          ["Volatility 25", "25%", "About 1.3%"],
          ["Volatility 50", "50%", "About 2.6%"],
          ["Volatility 75", "75%", "About 3.9%"],
          ["Volatility 100", "100%", "About 5.2%"],
        ],
      },
      { type: "h2", text: "Why it is so popular" },
      {
        type: "list",
        items: [
          "Large moves make it attractive for leveraged CFD trading, where a move is magnified.",
          "It has been widely promoted in strategy videos, signal groups and paid courses.",
          "It is always open.",
        ],
      },
      { type: "h2", text: "What that popularity hides" },
      {
        type: "p",
        text: "More volatility is not more opportunity. On a random index a bigger move is as likely to be against you as for you. With leverage, the distance to losing the whole position is shorter. With barrier options, a more volatile index makes touching a barrier more likely and the payout is adjusted to match. Nothing about the 75 makes it easier to profit from than the 10.",
      },
      { type: "h2", text: "Predictions, signals and strategies" },
      {
        type: "p",
        text: "Searches for Volatility 75 predictions and strategy PDFs are common. Deriv describes the index as generated by a cryptographically secure random number generator with no order book, and calls historical patterns coincidental. A prediction for a random series is a guess, and anyone selling one is selling the guess.",
      },
      { type: "h2", text: "Trading it sensibly" },
      {
        type: "list",
        items: [
          "Learn on a lower volatility index or on the demo account first.",
          "With options, the stake is the most a trade can lose. Keep it small against your session limit.",
          "With CFDs, size the position from the stop distance and use far less leverage than is offered.",
          "Test any bot again when you move it to this index from another.",
        ],
      },
      { type: "h2", text: "In FXNOD" },
      {
        type: "p",
        text: "Volatility 75 and Volatility 75 (1s) are among the markets Auto Hub's fade bots suggest, and both can be chosen in dTrader and dBot where your Deriv account offers them.",
      },
      SOURCE_NOTE,
      RISK_NOTE,
    ],
    faq: [
      {
        q: "What is the Volatility 75 Index based on?",
        a: "Nothing in the real world. It is a simulated price generated by an algorithm to hold a volatility of 75%.",
      },
      {
        q: "What is the difference between Volatility 75 and Volatility 75 (1s)?",
        a: "Tick speed. Deriv says volatility indices tick every two seconds on the normal versions and every second on the faster ones.",
      },
      {
        q: "Is there a best strategy for Volatility 75?",
        a: "No strategy predicts its direction. What you control is the stake, the contract and the limits.",
      },
      {
        q: "Can I trade Volatility 75 on MT5?",
        a: "Deriv lists CFDs on synthetic indices on Deriv MT5, Deriv cTrader and TradingView, and options on Deriv Trader and Deriv Bot.",
      },
    ],
    related: ["which-volatility-index-is-best", "how-volatility-affects-trading"],
  },

  {
    slug: "which-volatility-index-is-best",
    title: "Which volatility index is best to trade?",
    description:
      "No volatility index is easier to profit from than another. How to choose by the size of move, tick speed and your account size, with a comparison.",
    tag: TAG,
    published: DATE,
    updated: DATE,
    image: "/assets/login-slide-3.jpg",
    answer:
      "No volatility index is best in the sense of being easier to profit from: each is random and differs only in how far it moves and how often it ticks. Choose by what suits your account and temperament. Lower-numbered indices move less and are calmer to learn on. Higher-numbered and (1s) versions are faster in both directions.",
    body: [
      { type: "h2", text: "The two things that differ" },
      {
        type: "table",
        head: ["Setting", "Lower", "Higher"],
        rows: [
          ["Volatility level (10 to 250)", "Smaller moves per tick", "Larger moves per tick"],
          ["Tick speed", "Every 2 seconds", "Every second, on (1s) versions"],
        ],
      },
      { type: "h2", text: "Choosing by what you trade" },
      {
        type: "table",
        head: ["If you trade", "The index changes", "Consider"],
        rows: [
          ["Digit contracts", "Nothing about the odds: last digits are equally likely on any index", "Tick speed only. A (1s) index trades twice as often"],
          ["Rise/Fall", "Little: direction is close to even on all of them", "Tick speed and your patience"],
          ["Touch, Turbos, Accumulators", "A great deal: volatility decides how easily a barrier is reached", "Test on the exact index you will use"],
          ["Multipliers and CFDs", "The distance to stop out or to your stop", "A lower index and less leverage"],
        ],
      },
      { type: "h2", text: "For beginners" },
      {
        type: "p",
        text: "Start on a lower-volatility index with the normal tick speed, on the demo account. Slower ticks give you time to see how a contract settles, and smaller moves make mistakes with barriers and leverage less costly.",
      },
      { type: "h2", text: "For a small account" },
      {
        type: "p",
        text: "The index matters less than the product. With options the most a trade can lose is the stake, whichever index it is on, so a small account is protected by a small stake. With leveraged CFDs, a high-volatility index can exhaust a small balance on one position.",
      },
      { type: "h2", text: "For a bot" },
      {
        type: "list",
        items: [
          "A (1s) index roughly doubles the number of trades per hour, so the session reaches its stop loss or target in about half the time.",
          "Each trade carries a small cost on average. More trades means more cost.",
          "A bot tested on one index is untested on another.",
        ],
      },
      { type: "h2", text: "Claims to ignore" },
      {
        type: "list",
        items: [
          "That one index is more predictable.",
          "That an index has a pattern at certain hours.",
          "That a robot or indicator has been tuned to a particular index.",
        ],
      },
      SOURCE_NOTE,
      RISK_NOTE,
    ],
    faq: [
      {
        q: "Which volatility index is best for beginners?",
        a: "A lower-numbered one with the normal two-second tick, on a demo account. It moves less and more slowly.",
      },
      {
        q: "Which volatility index moves the most?",
        a: "The highest-numbered ones. Deriv says volatility levels run from 10% to 250%.",
      },
      {
        q: "Which volatility index is the most profitable?",
        a: "None is more profitable on average. They differ in size and speed of movement, not in how predictable they are.",
      },
    ],
    related: ["volatility-75-index-explained", "best-synthetic-index-for-a-small-account"],
  },

  {
    slug: "boom-and-crash-indices-explained",
    title: "Boom and Crash indices: how they work",
    description:
      "Boom indices surge and Crash indices drop suddenly, on average once per set number of ticks. What the number means and why spikes cannot be timed.",
    tag: TAG,
    published: DATE,
    updated: DATE,
    image: "/assets/login-slide-1.jpg",
    answer:
      "Boom and Crash are Deriv synthetic indices built around sudden moves. A Boom index produces rapid surges and a Crash index sudden downturns. The number in the name is the average number of ticks between those events: Boom 1000 surges on average once every 1,000 ticks. Average is the key word. The next one can come at any tick.",
    body: [
      { type: "h2", text: "Reading the name" },
      {
        type: "table",
        head: ["Index", "Event", "On average once every"],
        rows: [
          ["Boom 300", "Sudden surge", "300 ticks"],
          ["Boom 500", "Sudden surge", "500 ticks"],
          ["Boom 1000", "Sudden surge", "1,000 ticks"],
          ["Crash 300", "Sudden drop", "300 ticks"],
          ["Crash 500", "Sudden drop", "500 ticks"],
          ["Crash 1000", "Sudden drop", "1,000 ticks"],
        ],
      },
      {
        type: "p",
        text: "Deriv lists further frequencies, including 50, 150, 600 and 900. Its page does not state the size of a spike or drop, so check the specification of the exact index in your account.",
      },
      { type: "h2", text: "Why you cannot time a spike" },
      {
        type: "p",
        text: "An event that happens on average once per 1,000 ticks does not happen every 1,000 ticks. If each tick has the same small chance of a spike, the gaps between spikes vary enormously: about 10% of gaps are shorter than 105 ticks, half are shorter than 693, and about 5% are longer than 3,000. Having waited 900 ticks tells you nothing about the next 100. The index does not remember.",
      },
      {
        type: "table",
        head: ["Gap between spikes on a 1,000 index", "Share of gaps"],
        rows: [
          ["Under 105 ticks", "About 10%"],
          ["Under 693 ticks", "About 50%"],
          ["Over 1,000 ticks", "About 37%"],
          ["Over 3,000 ticks", "About 5%"],
        ],
      },
      {
        type: "p",
        text: "These shares follow from assuming an equal, independent chance on every tick. That is our illustration of what an average interval implies, not a statement from Deriv about its generator.",
      },
      { type: "h2", text: "The two popular approaches and their flaw" },
      {
        type: "list",
        items: [
          "Catching spikes: buying a Boom index or selling a Crash index and waiting. Each tick without a spike costs a little, and the wait can be several times the average.",
          "Riding the drift: trading the direction between spikes. Many small gains are given back, with more, when the spike arrives against the position.",
          "Both are the same trade seen from opposite sides, and neither has an edge on a random index.",
        ],
      },
      { type: "h2", text: "Spike indicators and killer robots" },
      {
        type: "p",
        text: "Searches for Boom and Crash spike detectors and killer EAs are common. If the timing of a spike is random, no indicator built from past prices can see it coming. Tools sold with that claim show past spikes after the fact.",
      },
      { type: "h2", text: "Risk" },
      {
        type: "list",
        items: [
          "A spike moves the price far in one tick, so a stop on a CFD can fill beyond its level.",
          "Leverage on these indices can be very high, which shortens the distance to losing the position.",
          "Practise on the demo account, and size every position for a spike against you.",
        ],
      },
      SOURCE_NOTE,
      RISK_NOTE,
    ],
    faq: [
      {
        q: "What does the number in Boom 1000 mean?",
        a: "The average number of ticks between surges. Deriv says the tick frequency sets how often, on average, the market will crash or boom.",
      },
      {
        q: "Can you predict Boom and Crash spikes?",
        a: "No. An average interval is not a schedule, and Deriv describes these indices as randomly generated.",
      },
      {
        q: "What is the difference between Boom and Crash?",
        a: "Direction. Boom indices have sudden surges upward and Crash indices sudden drops.",
      },
      {
        q: "Is there a spike detector that works?",
        a: "Nothing built from past prices can predict a random event. Be wary of anyone selling one.",
      },
    ],
    related: ["what-are-synthetic-indices", "gamblers-fallacy-in-trading"],
  },

  {
    slug: "step-index-explained",
    title: "Step Index on Deriv: what it is and how it moves",
    description:
      "A Step index moves up or down by a fixed amount on every tick. How the variants differ, what a random walk looks like, and what that means in practice.",
    tag: TAG,
    published: DATE,
    updated: DATE,
    image: "/assets/login-slide-2.jpg",
    answer:
      "A Step index is a Deriv synthetic index whose price moves up or down by a fixed amount on every tick. Deriv describes steps of 0.1, 0.2, 0.3, 0.4 or 0.5, depending on the variant. There are no large jumps and no changing volatility. Every tick is the same size; only the direction varies.",
    body: [
      { type: "h2", text: "The variants" },
      {
        type: "table",
        head: ["Family", "How it moves, according to Deriv"],
        rows: [
          ["Step", "Up or down by a fixed step of 0.1 to 0.5 on each tick"],
          ["Multi Step", "Usually by 0.1, and less often by 0.2, 0.25, 0.3 or 0.5"],
          ["Skew Step", "Small shifts most of the time, with an 80% or 90% probability, and sharp moves the rest"],
        ],
      },
      {
        type: "p",
        text: "Deriv's page does not state the probability of an up step against a down step on the standard Step index. Check the specification for the exact index before assuming anything about it.",
      },
      { type: "h2", text: "What a fixed step produces" },
      {
        type: "p",
        text: "A series that moves by the same amount each tick, in a random direction, is the textbook random walk. It still produces charts with long runs, channels and apparent trends, because random walks do. After 100 steps of 0.1 with an even chance each way, the price is typically about 1 away from where it started, and it could be anywhere within about 2 either side.",
      },
      {
        type: "table",
        head: ["Steps of 0.1", "Typical distance from the start", "Rarely more than"],
        rows: [
          ["100", "About 1.0", "About 2.0"],
          ["400", "About 2.0", "About 4.0"],
          ["10,000", "About 10", "About 20"],
        ],
      },
      {
        type: "p",
        text: "These figures assume an equal chance of up and down on each tick. They show the scale of drift that pure chance creates, and are not a specification from Deriv.",
      },
      { type: "h2", text: "Why traders like it" },
      {
        type: "list",
        items: [
          "No sudden spikes: the worst single tick is one step.",
          "A stop is unlikely to be jumped over, because the price cannot gap.",
          "The risk of a position is easy to calculate in steps.",
        ],
      },
      { type: "h2", text: "What it does not give you" },
      {
        type: "p",
        text: "Calm is not the same as predictable. A smooth chart invites trend lines and patterns, and on a random walk they have no forecasting value. The even pace also tempts traders into large positions, and a long run against a leveraged position does the same damage as a spike, only more slowly.",
      },
      { type: "h2", text: "Trading it" },
      {
        type: "list",
        items: [
          "Count risk in steps: stop distance in steps multiplied by the value of a step for your size.",
          "Use the demo account to see how long runs really last.",
          "Keep leverage low. A hundred steps against you is an ordinary event.",
        ],
      },
      SOURCE_NOTE,
      RISK_NOTE,
    ],
    faq: [
      {
        q: "What is a Step index?",
        a: "A synthetic index that moves up or down by a fixed amount on every tick, with no jumps.",
      },
      {
        q: "What is the difference between Step 100 and Step 500?",
        a: "The variants differ in step size, which Deriv gives as 0.1 to 0.5. Check the specification of each index in your account.",
      },
      {
        q: "Is the Step index easier to trade?",
        a: "It is steadier, with no spikes. Its direction is no easier to predict than any other synthetic index.",
      },
    ],
    related: ["what-are-synthetic-indices", "boom-and-crash-indices-explained"],
  },

  {
    slug: "are-synthetic-indices-manipulated",
    title: "Are synthetic indices manipulated?",
    description:
      "Deriv says its synthetic indices come from a secure random number generator with no order book. What can and cannot be verified, and where the real cost is.",
    tag: TAG,
    published: DATE,
    updated: DATE,
    image: "/assets/login-slide-3.jpg",
    answer:
      "Deriv states that its synthetic indices are generated by a cryptographically secure random number generator and that there is no order book. A trader cannot verify that independently, and neither can FXNOD. What can be said is that a broker has no need to manipulate individual prices: the cost built into every payout and spread already works in its favour.",
    body: [
      { type: "h2", text: "What Deriv says" },
      {
        type: "list",
        items: [
          "The indices are generated by a cryptographically secure random number generator.",
          "There is no order book, and historical patterns are coincidental.",
          "External news does not affect the price.",
          "Its trading terms say its pricing calculations include a bias in its favour.",
        ],
      },
      { type: "h2", text: "What nobody outside can check" },
      {
        type: "p",
        text: "A synthetic index exists only at the broker that runs it. There is no second venue to compare the price with and no public record of how each tick was produced. You are trusting the operator. That is a real difference from a currency pair, which thousands of institutions quote at once.",
      },
      { type: "h2", text: "Why it feels rigged" },
      {
        type: "table",
        head: ["What happens", "The ordinary explanation"],
        rows: [
          ["The price reverses just after you enter", "Half of all entries on a random series are followed by a move against them"],
          ["Your barrier is touched by one tick", "You remember near misses and forget the trades that cleared easily"],
          ["A long losing streak arrives after you raise the stake", "Streaks are frequent, and you raised the stake after one had started"],
          ["It won on demo and lost on real", "A short demo test did not include a bad stretch"],
          ["The spike came right after you closed", "Spike timing is random, so some will always follow your exit"],
        ],
      },
      { type: "h2", text: "Where the real disadvantage is" },
      {
        type: "p",
        text: "You do not need manipulation to lose steadily. An even-chance contract that pays a profit of 95 on a stake of 100 costs about 2.5 per 100 staked on average, on every trade. A thousand trades at a stake of 1 is an expected cost of about 25. That cost is in plain view in the payout, and it is what empties accounts.",
      },
      { type: "h2", text: "How to test fairness yourself" },
      {
        type: "steps",
        items: [
          { title: "Record a large sample", text: "For example, the last digit of 5,000 ticks on a demo account." },
          { title: "Compare with chance", text: "Each digit should appear about 500 times, typically between 460 and 540." },
          { title: "Check your own trades", text: "Over several hundred Even/Odd trades the win rate should be close to 50%." },
        ],
      },
      {
        type: "p",
        text: "A test like this can reveal a crude bias. It cannot prove fairness, and it says nothing about whether the payouts are generous.",
      },
      { type: "h2", text: "The sensible conclusion" },
      {
        type: "list",
        items: [
          "Treat the index as random and the payout as priced against you.",
          "Do not look for the trick that beats it. Control the stake and the limits.",
          "If trust in a single operator bothers you, trade a real market at a strongly regulated broker.",
        ],
      },
      SOURCE_NOTE,
      RISK_NOTE,
    ],
    faq: [
      {
        q: "Does Deriv trade against its clients?",
        a: "On synthetic indices there is no external market, so the broker is the other side of the trade. Its terms say the pricing includes a bias in its favour.",
      },
      {
        q: "Can Deriv see my trades and move the price?",
        a: "Deriv states the indices come from a random number generator. That cannot be verified from outside, and the built-in cost means it has no need to.",
      },
      {
        q: "Are synthetic indices audited?",
        a: `Deriv's synthetic indices page made no mention of an audit when it was read for this guide. Ask Deriv directly if this matters to you.`,
      },
    ],
    related: ["what-are-synthetic-indices", "is-deriv-legit"],
  },

  {
    slug: "options-vs-cfds",
    title: "Options vs CFDs: what is the difference?",
    description:
      "An option risks a fixed stake for a set payout. A CFD follows the price with leverage and an open-ended result. Side by side, with who each suits.",
    tag: TAG,
    published: DATE,
    updated: DATE,
    image: "/assets/login-slide-1.jpg",
    answer:
      "An option is a contract with a fixed cost: you pay a stake, and the most you can lose is that stake. A CFD, or contract for difference, tracks the price of a market with leverage: profit and loss grow with every point the price moves and are not fixed in advance. Options limit the loss per trade. CFDs do not, unless you set a stop.",
    body: [
      { type: "h2", text: "Side by side" },
      {
        type: "table",
        head: ["", "Options (as offered by Deriv)", "CFDs"],
        rows: [
          ["What you pay", "A stake", "Margin, a fraction of the position"],
          ["Most you can lose on a trade", "The stake", "Depends on size, leverage and your stop"],
          ["Profit", "Set by the contract's payout", "Grows with the price move"],
          ["Ends", "At expiry, or when a barrier is hit", "When you close it or are stopped out"],
          ["Costs", "Built into the payout", "Spread, commission and overnight swap"],
          ["Leverage", "None in the usual sense", "Yes, often high"],
          ["Being roughly right", "Often pays nothing", "Pays in proportion"],
        ],
      },
      { type: "h2", text: "How the risk feels different" },
      {
        type: "p",
        text: "With an option, the worst case is known before you buy. The danger is repetition: many small total losses add up fast, especially on contracts lasting seconds. With a CFD, a single position can lose far more than you intended if it is too large or has no stop. The danger is one trade.",
      },
      { type: "h2", text: "What each rewards" },
      {
        type: "list",
        items: [
          "Options reward being right about a specific outcome by a specific time.",
          "CFDs reward being right about direction, and let you hold while you are.",
          "A fixed-payout option pays the same whether the price barely crosses the line or runs far past it.",
          "A CFD pays more the further the price goes, and costs more the further it goes against you.",
        ],
      },
      { type: "h2", text: "Who each suits" },
      {
        type: "table",
        head: ["If you", "Consider"],
        rows: [
          ["Are starting and want a capped loss per trade", "Options, on a demo account first"],
          ["Want to automate very short trades", "Options"],
          ["Analyse real markets and hold for hours or days", "CFDs, with careful position sizing"],
          ["Do not yet understand margin and leverage", "Not CFDs"],
        ],
      },
      { type: "h2", text: "On Deriv and in FXNOD" },
      {
        type: "p",
        text: "Deriv lists options on Deriv Trader and Deriv Bot, and CFDs on Deriv MT5, Deriv cTrader and TradingView. It warns that CFDs carry a high risk of losing money rapidly due to leverage. FXNOD's dTrader, dBot and Auto Hub trade options and multipliers on your Deriv account. They do not trade CFDs.",
      },
      SOURCE_NOTE,
      RISK_NOTE,
    ],
    faq: [
      {
        q: "Are options safer than CFDs?",
        a: "The loss on a single option is capped at the stake, which a CFD's is not. Options can still empty an account through many losing trades.",
      },
      {
        q: "Are options and CFDs the same?",
        a: "No. An option has a fixed cost and a defined outcome. A CFD is an open position whose profit or loss follows the price.",
      },
      {
        q: "Which is better for beginners, options or CFDs?",
        a: "Options are simpler to reason about because the loss per trade is fixed. Learn either on a demo account.",
      },
      {
        q: "What is a multiplier, then?",
        a: "A product between the two: it follows the price with a multiplier like a CFD, and caps the loss at the stake like an option.",
      },
    ],
    related: ["multipliers-explained", "what-is-payout-in-trading"],
  },

  {
    slug: "what-is-payout-in-trading",
    title: "What is payout in trading?",
    description:
      "Payout is what a winning contract returns: your stake plus the profit. How to read it, turn it into a break-even win rate, and compare contracts.",
    tag: TAG,
    published: DATE,
    updated: DATE,
    image: "/assets/login-slide-2.jpg",
    answer:
      "The payout is the total amount a winning contract returns, usually your stake plus the profit. If you stake 10 and the payout is 19.50, the profit is 9.50. The payout tells you the win rate you need to break even: divide the stake by the payout. Here that is 10 divided by 19.50, or 51.3%.",
    body: [
      { type: "h2", text: "Payout, profit and return" },
      {
        type: "table",
        head: ["Term", "Meaning", "Example on a stake of 10"],
        rows: [
          ["Stake", "What you pay for the contract", "10"],
          ["Payout", "What you receive if it wins", "19.50"],
          ["Profit", "Payout minus stake", "9.50"],
          ["Return", "Profit as a share of the stake", "95%"],
        ],
      },
      {
        type: "p",
        text: "Platforms differ in which of these they show. Check whether a quoted figure includes your stake before comparing two contracts.",
      },
      { type: "h2", text: "From payout to break-even" },
      {
        type: "table",
        head: ["Payout on a stake of 10", "Return", "Win rate needed to break even"],
        rows: [
          ["11.00", "10%", "90.9%"],
          ["12.50", "25%", "80.0%"],
          ["15.00", "50%", "66.7%"],
          ["19.50", "95%", "51.3%"],
          ["30.00", "200%", "33.3%"],
          ["100.00", "900%", "10.0%"],
        ],
      },
      {
        type: "p",
        text: "Break-even win rate equals stake divided by payout. Compare it with the true chance of winning. The difference between them is the cost of the contract.",
      },
      { type: "h2", text: "Where the cost hides" },
      {
        type: "p",
        text: "A contract with a true 50% chance would be fair at a payout of 20 on a stake of 10. At 19.50 it costs 0.25 per trade on average. A contract with a true 90% chance would be fair at 11.11, and at 11.00 it costs 0.10 per trade. Neither figure appears on the screen. You find it by working out the fair payout and comparing.",
      },
      { type: "h2", text: "Payout per point" },
      {
        type: "p",
        text: "On turbos and vanillas the payout is not fixed. Deriv quotes a payout per point, and the payout is that figure multiplied by how far the final price is from the barrier or strike. You profit only when the payout exceeds the stake.",
      },
      { type: "h2", text: "Other meanings" },
      {
        type: "list",
        items: [
          "With prop firms, a payout is a withdrawal of the trader's share of profits.",
          "With brokers, a payout sometimes means a withdrawal to your bank.",
          "A payoff ratio is the average win divided by the average loss.",
        ],
      },
      { type: "h2", text: "In FXNOD" },
      {
        type: "p",
        text: "dTrader's order panel shows what Deriv will pay for exactly the settings you chose, and the quote changes when you change anything. Read it before every purchase.",
      },
      RISK_NOTE,
    ],
    faq: [
      {
        q: "Does payout include my stake?",
        a: "On Deriv-style options, the payout is the total returned on a win, including the stake. Other platforms may quote profit only.",
      },
      {
        q: "What is a good payout?",
        a: "One whose break-even win rate is below the win rate you can really achieve. On random markets the payout is set so that it is not.",
      },
      {
        q: "Why does the payout change?",
        a: "It depends on the contract's settings and the market at that moment: duration, barrier, volatility and the broker's pricing.",
      },
    ],
    related: ["risk-to-reward-ratio", "is-a-high-win-rate-enough"],
  },

  {
    slug: "best-synthetic-index-for-a-small-account",
    title: "Best synthetic index for a small account",
    description:
      "With a small account the product matters more than the index. Why options with a tiny stake suit it, what to avoid, and a worked 20-dollar example.",
    tag: TAG,
    published: DATE,
    updated: DATE,
    image: "/assets/login-slide-3.jpg",
    answer:
      "For a small account, the choice of product matters more than the choice of index. Options let you risk a very small fixed stake on any synthetic index, so a small balance lasts many trades. Leveraged CFDs on high-volatility indices can exhaust a small balance on a single position. If in doubt: a lower-volatility index, options, and the minimum stake.",
    body: [
      { type: "h2", text: "What a small account needs" },
      {
        type: "list",
        items: [
          "Many trades for the money, so that one bad run does not end it.",
          "A loss per trade that is fixed and tiny.",
          "No leverage.",
        ],
      },
      { type: "h2", text: "A worked example with 20" },
      {
        type: "table",
        head: ["Stake", "Share of the account", "Losses in a row that empty it", "Chance of that streak in a 50% trade sequence"],
        rows: [
          ["5", "25%", "4", "1 in 16"],
          ["2", "10%", "10", "1 in 1,024"],
          ["1", "5%", "20", "About 1 in a million"],
          ["0.35", "1.75%", "57", "Negligible"],
        ],
      },
      {
        type: "p",
        text: "The last column is for one unbroken streak. In practice an account is worn down by a net excess of losses over time, which is far more likely than a perfect streak. The lesson is the same: the smaller the stake against the balance, the longer you last and the more you learn.",
      },
      { type: "h2", text: "Why the index matters less than you think" },
      {
        type: "p",
        text: "On an option, a loss costs the stake whether the index is Volatility 10 or Volatility 250. Last-digit odds are the same on every index. For those contracts, choose a slower two-second index simply to place fewer trades per hour.",
      },
      { type: "h2", text: "What to avoid" },
      {
        type: "list",
        items: [
          "CFDs with high leverage. A small balance cannot absorb a normal swing.",
          "Martingale. A small account cannot fund the later steps of the ladder.",
          "Bots sold as made for small accounts. The phrase usually means a low base stake on a doubling system.",
          "Depositing more to recover.",
        ],
      },
      { type: "h2", text: "Honest expectations" },
      {
        type: "p",
        text: "A small account is for learning, not for income. A 20-unit account cannot be turned into a living wage by any method that is not mostly luck. Use it to practise discipline with real money at a cost you chose in advance.",
      },
      { type: "h2", text: "In FXNOD" },
      {
        type: "p",
        text: "Auto Hub's digit bots accept a stake down to 0.35, which FXNOD's guide gives as Deriv's minimum for those contracts, always use the same stake, and require a stop loss. Run them on the demo account first.",
      },
      SOURCE_NOTE,
      RISK_NOTE,
    ],
    faq: [
      {
        q: "Can I trade synthetic indices with 10 dollars?",
        a: "With options and a minimum stake, yes: you can place many trades. With leveraged CFDs, a balance that size can be lost on one move.",
      },
      {
        q: "Which Deriv bot is best for a small account?",
        a: "One with a flat stake at the minimum and a stop loss. Avoid any bot that raises the stake after a loss.",
      },
      {
        q: "How do I grow a small account fast?",
        a: "You cannot do it reliably. Fast growth requires large risk, and large risk on a small account usually ends it.",
      },
    ],
    related: ["which-volatility-index-is-best", "flat-stake-explained"],
  },
];
