/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision â€” parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EmailUpdateConfirmRequest,
  EmailUpdateRequest,
  Error,
  KYCStatusResponse,
  KYCSubmission,
  PasswordVerifyRequest,
  RequestEmailUpdate200,
  UnauthorizedResponse,
  UserPublic,
  UserUpdate,
  ValidationErrorResponse,
  VerifyCurrentPassword200
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType , BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get current user profile
 */
export const getMe = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserPublic>(
      {url: `/api/v1/users/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMeQueryKey = () => {
    return [
    `/api/v1/users/me`
    ] as const;
    }

    
export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<UnauthorizedResponse>


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user profile
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Updates profile fields and emits a version-bumped USER_UPDATED event.
 * @summary Update current user profile
 */
export const updateMe = (
    userUpdate: BodyType<UserUpdate>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UserPublic>(
      {url: `/api/v1/users/me`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userUpdate
    },
      options);
    }
  


export const getUpdateMeMutationOptions = <TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: BodyType<UserUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: BodyType<UserUpdate>}, TContext> => {

const mutationKey = ['updateMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMe>>, {data: BodyType<UserUpdate>}> = (props) => {
          const {data} = props ?? {};

          return  updateMe(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMeMutationResult = NonNullable<Awaited<ReturnType<typeof updateMe>>>
    export type UpdateMeMutationBody = BodyType<UserUpdate>
    export type UpdateMeMutationError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>

    /**
 * @summary Update current user profile
 */
export const useUpdateMe = <TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: BodyType<UserUpdate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMe>>,
        TError,
        {data: BodyType<UserUpdate>},
        TContext
      > => {

      const mutationOptions = getUpdateMeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Verifies the current user's password before sensitive operations.
 * @summary Verify current password
 */
export const verifyCurrentPassword = (
    passwordVerifyRequest: BodyType<PasswordVerifyRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<VerifyCurrentPassword200>(
      {url: `/api/v1/users/me/verify-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordVerifyRequest, signal
    },
      options);
    }
  


export const getVerifyCurrentPasswordMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCurrentPassword>>, TError,{data: BodyType<PasswordVerifyRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyCurrentPassword>>, TError,{data: BodyType<PasswordVerifyRequest>}, TContext> => {

const mutationKey = ['verifyCurrentPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyCurrentPassword>>, {data: BodyType<PasswordVerifyRequest>}> = (props) => {
          const {data} = props ?? {};

          return  verifyCurrentPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyCurrentPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof verifyCurrentPassword>>>
    export type VerifyCurrentPasswordMutationBody = BodyType<PasswordVerifyRequest>
    export type VerifyCurrentPasswordMutationError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>

    /**
 * @summary Verify current password
 */
export const useVerifyCurrentPassword = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCurrentPassword>>, TError,{data: BodyType<PasswordVerifyRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyCurrentPassword>>,
        TError,
        {data: BodyType<PasswordVerifyRequest>},
        TContext
      > => {

      const mutationOptions = getVerifyCurrentPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Initiates an email update by sending an OTP to the new email address.
 * @summary Request an email update
 */
export const requestEmailUpdate = (
    emailUpdateRequest: BodyType<EmailUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RequestEmailUpdate200>(
      {url: `/api/v1/users/me/request-email-update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailUpdateRequest, signal
    },
      options);
    }
  


export const getRequestEmailUpdateMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestEmailUpdate>>, TError,{data: BodyType<EmailUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof requestEmailUpdate>>, TError,{data: BodyType<EmailUpdateRequest>}, TContext> => {

const mutationKey = ['requestEmailUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestEmailUpdate>>, {data: BodyType<EmailUpdateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  requestEmailUpdate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RequestEmailUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof requestEmailUpdate>>>
    export type RequestEmailUpdateMutationBody = BodyType<EmailUpdateRequest>
    export type RequestEmailUpdateMutationError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>

    /**
 * @summary Request an email update
 */
export const useRequestEmailUpdate = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestEmailUpdate>>, TError,{data: BodyType<EmailUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof requestEmailUpdate>>,
        TError,
        {data: BodyType<EmailUpdateRequest>},
        TContext
      > => {

      const mutationOptions = getRequestEmailUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Verifies the OTP and finalizes the email update for the current user.
 * @summary Confirm email update
 */
export const confirmEmailUpdate = (
    emailUpdateConfirmRequest: BodyType<EmailUpdateConfirmRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserPublic>(
      {url: `/api/v1/users/me/confirm-email-update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailUpdateConfirmRequest, signal
    },
      options);
    }
  


export const getConfirmEmailUpdateMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmEmailUpdate>>, TError,{data: BodyType<EmailUpdateConfirmRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmEmailUpdate>>, TError,{data: BodyType<EmailUpdateConfirmRequest>}, TContext> => {

const mutationKey = ['confirmEmailUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmEmailUpdate>>, {data: BodyType<EmailUpdateConfirmRequest>}> = (props) => {
          const {data} = props ?? {};

          return  confirmEmailUpdate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmEmailUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof confirmEmailUpdate>>>
    export type ConfirmEmailUpdateMutationBody = BodyType<EmailUpdateConfirmRequest>
    export type ConfirmEmailUpdateMutationError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>

    /**
 * @summary Confirm email update
 */
export const useConfirmEmailUpdate = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmEmailUpdate>>, TError,{data: BodyType<EmailUpdateConfirmRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmEmailUpdate>>,
        TError,
        {data: BodyType<EmailUpdateConfirmRequest>},
        TContext
      > => {

      const mutationOptions = getConfirmEmailUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Requires a verified email.
 * @summary Submit a KYC document
 */
export const submitKyc = (
    kYCSubmission: BodyType<KYCSubmission>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<KYCStatusResponse>(
      {url: `/api/v1/users/kyc`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: kYCSubmission, signal
    },
      options);
    }
  


export const getSubmitKycMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitKyc>>, TError,{data: BodyType<KYCSubmission>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof submitKyc>>, TError,{data: BodyType<KYCSubmission>}, TContext> => {

const mutationKey = ['submitKyc'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitKyc>>, {data: BodyType<KYCSubmission>}> = (props) => {
          const {data} = props ?? {};

          return  submitKyc(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SubmitKycMutationResult = NonNullable<Awaited<ReturnType<typeof submitKyc>>>
    export type SubmitKycMutationBody = BodyType<KYCSubmission>
    export type SubmitKycMutationError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>

    /**
 * @summary Submit a KYC document
 */
export const useSubmitKyc = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitKyc>>, TError,{data: BodyType<KYCSubmission>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitKyc>>,
        TError,
        {data: BodyType<KYCSubmission>},
        TContext
      > => {

      const mutationOptions = getSubmitKycMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get KYC status
 */
export const getKycStatus = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<KYCStatusResponse>(
      {url: `/api/v1/users/kyc/status`, method: 'GET', signal
    },
      options);
    }
  



export const getGetKycStatusQueryKey = () => {
    return [
    `/api/v1/users/kyc/status`
    ] as const;
    }

    
export const getGetKycStatusQueryOptions = <TData = Awaited<ReturnType<typeof getKycStatus>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKycStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetKycStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getKycStatus>>> = ({ signal }) => getKycStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getKycStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetKycStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getKycStatus>>>
export type GetKycStatusQueryError = ErrorType<UnauthorizedResponse>


export function useGetKycStatus<TData = Awaited<ReturnType<typeof getKycStatus>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKycStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getKycStatus>>,
          TError,
          Awaited<ReturnType<typeof getKycStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetKycStatus<TData = Awaited<ReturnType<typeof getKycStatus>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKycStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getKycStatus>>,
          TError,
          Awaited<ReturnType<typeof getKycStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetKycStatus<TData = Awaited<ReturnType<typeof getKycStatus>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKycStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get KYC status
 */

export function useGetKycStatus<TData = Awaited<ReturnType<typeof getKycStatus>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKycStatus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetKycStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




