/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BalanceResponse,
  BinancePayOrderCreateRequest,
  BinancePayOrderCreateResponse,
  ChainDepositResponse,
  DepositAddressRequest,
  DepositAddressResponse,
  Error,
  GetWalletTransactionsParams,
  ListChainDepositsParams,
  ManualDepositCreate,
  ManualDepositResponse,
  TransactionHistoryResponse,
  UnauthorizedResponse,
  ValidationErrorResponse,
  WithdrawalRequestIn,
  WithdrawalRequestOut
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType , BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get wallet balance
 */
export const getWalletBalance = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BalanceResponse>(
      {url: `/api/v1/wallet/balance`, method: 'GET', signal
    },
      options);
    }
  



export const getGetWalletBalanceQueryKey = () => {
    return [
    `/api/v1/wallet/balance`
    ] as const;
    }

    
export const getGetWalletBalanceQueryOptions = <TData = Awaited<ReturnType<typeof getWalletBalance>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletBalanceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletBalance>>> = ({ signal }) => getWalletBalance(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWalletBalance>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWalletBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletBalance>>>
export type GetWalletBalanceQueryError = ErrorType<UnauthorizedResponse>


export function useGetWalletBalance<TData = Awaited<ReturnType<typeof getWalletBalance>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletBalance>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletBalance>>,
          TError,
          Awaited<ReturnType<typeof getWalletBalance>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWalletBalance<TData = Awaited<ReturnType<typeof getWalletBalance>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletBalance>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletBalance>>,
          TError,
          Awaited<ReturnType<typeof getWalletBalance>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWalletBalance<TData = Awaited<ReturnType<typeof getWalletBalance>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get wallet balance
 */

export function useGetWalletBalance<TData = Awaited<ReturnType<typeof getWalletBalance>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletBalance>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWalletBalanceQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary List wallet transactions
 */
export const getWalletTransactions = (
    params?: GetWalletTransactionsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TransactionHistoryResponse>(
      {url: `/api/v1/wallet/transactions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetWalletTransactionsQueryKey = (params?: GetWalletTransactionsParams,) => {
    return [
    `/api/v1/wallet/transactions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetWalletTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getWalletTransactions>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(params?: GetWalletTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletTransactionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWalletTransactions>>> = ({ signal }) => getWalletTransactions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWalletTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getWalletTransactions>>>
export type GetWalletTransactionsQueryError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>


export function useGetWalletTransactions<TData = Awaited<ReturnType<typeof getWalletTransactions>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params: undefined |  GetWalletTransactionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletTransactions>>,
          TError,
          Awaited<ReturnType<typeof getWalletTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWalletTransactions<TData = Awaited<ReturnType<typeof getWalletTransactions>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params?: GetWalletTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWalletTransactions>>,
          TError,
          Awaited<ReturnType<typeof getWalletTransactions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWalletTransactions<TData = Awaited<ReturnType<typeof getWalletTransactions>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params?: GetWalletTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List wallet transactions
 */

export function useGetWalletTransactions<TData = Awaited<ReturnType<typeof getWalletTransactions>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params?: GetWalletTransactionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWalletTransactions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWalletTransactionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get or create a deposit address
 */
export const getOrCreateDepositAddress = (
    depositAddressRequest: BodyType<DepositAddressRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DepositAddressResponse>(
      {url: `/api/v1/wallet/deposit/address`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: depositAddressRequest, signal
    },
      options);
    }
  


export const getGetOrCreateDepositAddressMutationOptions = <TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getOrCreateDepositAddress>>, TError,{data: BodyType<DepositAddressRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getOrCreateDepositAddress>>, TError,{data: BodyType<DepositAddressRequest>}, TContext> => {

const mutationKey = ['getOrCreateDepositAddress'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getOrCreateDepositAddress>>, {data: BodyType<DepositAddressRequest>}> = (props) => {
          const {data} = props ?? {};

          return  getOrCreateDepositAddress(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetOrCreateDepositAddressMutationResult = NonNullable<Awaited<ReturnType<typeof getOrCreateDepositAddress>>>
    export type GetOrCreateDepositAddressMutationBody = BodyType<DepositAddressRequest>
    export type GetOrCreateDepositAddressMutationError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>

    /**
 * @summary Get or create a deposit address
 */
export const useGetOrCreateDepositAddress = <TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getOrCreateDepositAddress>>, TError,{data: BodyType<DepositAddressRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getOrCreateDepositAddress>>,
        TError,
        {data: BodyType<DepositAddressRequest>},
        TContext
      > => {

      const mutationOptions = getGetOrCreateDepositAddressMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Deposits detected on chain, including ones still confirming. Scoped to the authenticated user. Every status other than `credited` carries a `status_reason` explaining why no balance was added.
 * @summary List the caller's on-chain deposits
 */
export const listChainDeposits = (
    params?: ListChainDepositsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ChainDepositResponse[]>(
      {url: `/api/v1/wallet/deposits`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListChainDepositsQueryKey = (params?: ListChainDepositsParams,) => {
    return [
    `/api/v1/wallet/deposits`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListChainDepositsQueryOptions = <TData = Awaited<ReturnType<typeof listChainDeposits>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(params?: ListChainDepositsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChainDeposits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListChainDepositsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listChainDeposits>>> = ({ signal }) => listChainDeposits(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listChainDeposits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListChainDepositsQueryResult = NonNullable<Awaited<ReturnType<typeof listChainDeposits>>>
export type ListChainDepositsQueryError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>


export function useListChainDeposits<TData = Awaited<ReturnType<typeof listChainDeposits>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params: undefined |  ListChainDepositsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChainDeposits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChainDeposits>>,
          TError,
          Awaited<ReturnType<typeof listChainDeposits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChainDeposits<TData = Awaited<ReturnType<typeof listChainDeposits>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params?: ListChainDepositsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChainDeposits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChainDeposits>>,
          TError,
          Awaited<ReturnType<typeof listChainDeposits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListChainDeposits<TData = Awaited<ReturnType<typeof listChainDeposits>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params?: ListChainDepositsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChainDeposits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the caller's on-chain deposits
 */

export function useListChainDeposits<TData = Awaited<ReturnType<typeof listChainDeposits>>, TError = ErrorType<UnauthorizedResponse | ValidationErrorResponse>>(
 params?: ListChainDepositsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listChainDeposits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListChainDepositsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Records an intent to pay. Creates no balance — payment is confirmed only by a signed callback from Binance on /api/v1/webhooks/binancepay, never by the client reporting success.

`prepay_id` and `checkout_url` are null until the Binance order API is wired up. Returns 503 while the integration is unconfigured.
 * @summary Open a Binance Pay order
 */
export const createBinancePayOrder = (
    binancePayOrderCreateRequest: BodyType<BinancePayOrderCreateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BinancePayOrderCreateResponse>(
      {url: `/api/v1/wallet/deposit/binancepay`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: binancePayOrderCreateRequest, signal
    },
      options);
    }
  


export const getCreateBinancePayOrderMutationOptions = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBinancePayOrder>>, TError,{data: BodyType<BinancePayOrderCreateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createBinancePayOrder>>, TError,{data: BodyType<BinancePayOrderCreateRequest>}, TContext> => {

const mutationKey = ['createBinancePayOrder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBinancePayOrder>>, {data: BodyType<BinancePayOrderCreateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createBinancePayOrder(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBinancePayOrderMutationResult = NonNullable<Awaited<ReturnType<typeof createBinancePayOrder>>>
    export type CreateBinancePayOrderMutationBody = BodyType<BinancePayOrderCreateRequest>
    export type CreateBinancePayOrderMutationError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>

    /**
 * @summary Open a Binance Pay order
 */
export const useCreateBinancePayOrder = <TError = ErrorType<Error | UnauthorizedResponse | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBinancePayOrder>>, TError,{data: BodyType<BinancePayOrderCreateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBinancePayOrder>>,
        TError,
        {data: BodyType<BinancePayOrderCreateRequest>},
        TContext
      > => {

      const mutationOptions = getCreateBinancePayOrderMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Fallback for deposits the chain monitor did not detect. Creates a request for operator review — never a credit. `amount` is the user's unverified claim; what is actually paid out is decided at approval.

Rejects a transaction hash the monitor has already seen, which would otherwise be a route to being credited twice for one transfer.
 * @summary Submit a manual deposit claim
 */
export const createManualDeposit = (
    manualDepositCreate: BodyType<ManualDepositCreate>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ManualDepositResponse>(
      {url: `/api/v1/wallet/deposit/manual`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: manualDepositCreate, signal
    },
      options);
    }
  


export const getCreateManualDepositMutationOptions = <TError = ErrorType<UnauthorizedResponse | Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createManualDeposit>>, TError,{data: BodyType<ManualDepositCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createManualDeposit>>, TError,{data: BodyType<ManualDepositCreate>}, TContext> => {

const mutationKey = ['createManualDeposit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createManualDeposit>>, {data: BodyType<ManualDepositCreate>}> = (props) => {
          const {data} = props ?? {};

          return  createManualDeposit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateManualDepositMutationResult = NonNullable<Awaited<ReturnType<typeof createManualDeposit>>>
    export type CreateManualDepositMutationBody = BodyType<ManualDepositCreate>
    export type CreateManualDepositMutationError = ErrorType<UnauthorizedResponse | Error | ValidationErrorResponse>

    /**
 * @summary Submit a manual deposit claim
 */
export const useCreateManualDeposit = <TError = ErrorType<UnauthorizedResponse | Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createManualDeposit>>, TError,{data: BodyType<ManualDepositCreate>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createManualDeposit>>,
        TError,
        {data: BodyType<ManualDepositCreate>},
        TContext
      > => {

      const mutationOptions = getCreateManualDepositMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Request a withdrawal
 */
export const requestWithdrawal = (
    withdrawalRequestIn: BodyType<WithdrawalRequestIn>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<WithdrawalRequestOut>(
      {url: `/api/v1/wallet/withdraw`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: withdrawalRequestIn, signal
    },
      options);
    }
  


export const getRequestWithdrawalMutationOptions = <TError = ErrorType<UnauthorizedResponse | Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestWithdrawal>>, TError,{data: BodyType<WithdrawalRequestIn>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof requestWithdrawal>>, TError,{data: BodyType<WithdrawalRequestIn>}, TContext> => {

const mutationKey = ['requestWithdrawal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestWithdrawal>>, {data: BodyType<WithdrawalRequestIn>}> = (props) => {
          const {data} = props ?? {};

          return  requestWithdrawal(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RequestWithdrawalMutationResult = NonNullable<Awaited<ReturnType<typeof requestWithdrawal>>>
    export type RequestWithdrawalMutationBody = BodyType<WithdrawalRequestIn>
    export type RequestWithdrawalMutationError = ErrorType<UnauthorizedResponse | Error | ValidationErrorResponse>

    /**
 * @summary Request a withdrawal
 */
export const useRequestWithdrawal = <TError = ErrorType<UnauthorizedResponse | Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestWithdrawal>>, TError,{data: BodyType<WithdrawalRequestIn>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof requestWithdrawal>>,
        TError,
        {data: BodyType<WithdrawalRequestIn>},
        TContext
      > => {

      const mutationOptions = getRequestWithdrawalMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List the user's withdrawals
 */
export const listWithdrawals = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<WithdrawalRequestOut[]>(
      {url: `/api/v1/wallet/withdrawals`, method: 'GET', signal
    },
      options);
    }
  



export const getListWithdrawalsQueryKey = () => {
    return [
    `/api/v1/wallet/withdrawals`
    ] as const;
    }

    
export const getListWithdrawalsQueryOptions = <TData = Awaited<ReturnType<typeof listWithdrawals>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWithdrawalsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWithdrawals>>> = ({ signal }) => listWithdrawals(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWithdrawals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListWithdrawalsQueryResult = NonNullable<Awaited<ReturnType<typeof listWithdrawals>>>
export type ListWithdrawalsQueryError = ErrorType<UnauthorizedResponse>


export function useListWithdrawals<TData = Awaited<ReturnType<typeof listWithdrawals>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWithdrawals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWithdrawals>>,
          TError,
          Awaited<ReturnType<typeof listWithdrawals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWithdrawals<TData = Awaited<ReturnType<typeof listWithdrawals>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWithdrawals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWithdrawals>>,
          TError,
          Awaited<ReturnType<typeof listWithdrawals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWithdrawals<TData = Awaited<ReturnType<typeof listWithdrawals>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the user's withdrawals
 */

export function useListWithdrawals<TData = Awaited<ReturnType<typeof listWithdrawals>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWithdrawals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListWithdrawalsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




