/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetMySubscriptionParams,
  ListSubscriptionPlansParams,
  SubscriptionPlanListResponse,
  SubscriptionPurchaseRequest,
  SubscriptionPurchaseResponse,
  SubscriptionStatusResponse,
  UnauthorizedResponse,
  ValidationErrorResponse
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType , BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * The catalogue as the server sees it. Retired plans are excluded, so a stale page cannot buy something that is no longer sold. The client renders these prices and never sends one back.

 * @summary List the purchasable plans for a product
 */
export const listSubscriptionPlans = (
    params?: ListSubscriptionPlansParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SubscriptionPlanListResponse>(
      {url: `/api/v1/wallet/subscriptions/plans`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListSubscriptionPlansQueryKey = (params?: ListSubscriptionPlansParams,) => {
    return [
    `/api/v1/wallet/subscriptions/plans`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListSubscriptionPlansQueryOptions = <TData = Awaited<ReturnType<typeof listSubscriptionPlans>>, TError = ErrorType<UnauthorizedResponse>>(params?: ListSubscriptionPlansParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubscriptionPlans>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSubscriptionPlansQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSubscriptionPlans>>> = ({ signal }) => listSubscriptionPlans(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSubscriptionPlans>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSubscriptionPlansQueryResult = NonNullable<Awaited<ReturnType<typeof listSubscriptionPlans>>>
export type ListSubscriptionPlansQueryError = ErrorType<UnauthorizedResponse>


export function useListSubscriptionPlans<TData = Awaited<ReturnType<typeof listSubscriptionPlans>>, TError = ErrorType<UnauthorizedResponse>>(
 params: undefined |  ListSubscriptionPlansParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubscriptionPlans>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSubscriptionPlans>>,
          TError,
          Awaited<ReturnType<typeof listSubscriptionPlans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSubscriptionPlans<TData = Awaited<ReturnType<typeof listSubscriptionPlans>>, TError = ErrorType<UnauthorizedResponse>>(
 params?: ListSubscriptionPlansParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubscriptionPlans>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSubscriptionPlans>>,
          TError,
          Awaited<ReturnType<typeof listSubscriptionPlans>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSubscriptionPlans<TData = Awaited<ReturnType<typeof listSubscriptionPlans>>, TError = ErrorType<UnauthorizedResponse>>(
 params?: ListSubscriptionPlansParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubscriptionPlans>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List the purchasable plans for a product
 */

export function useListSubscriptionPlans<TData = Awaited<ReturnType<typeof listSubscriptionPlans>>, TError = ErrorType<UnauthorizedResponse>>(
 params?: ListSubscriptionPlansParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubscriptionPlans>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSubscriptionPlansQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * `entitled` is computed from the clock rather than from the stored status, so a lapsed subscription reads as lapsed the moment it does, whether or not any job has marked the row expired.

 * @summary The caller's own subscription for a product
 */
export const getMySubscription = (
    params?: GetMySubscriptionParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SubscriptionStatusResponse>(
      {url: `/api/v1/wallet/subscriptions/me`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetMySubscriptionQueryKey = (params?: GetMySubscriptionParams,) => {
    return [
    `/api/v1/wallet/subscriptions/me`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetMySubscriptionQueryOptions = <TData = Awaited<ReturnType<typeof getMySubscription>>, TError = ErrorType<UnauthorizedResponse>>(params?: GetMySubscriptionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMySubscriptionQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMySubscription>>> = ({ signal }) => getMySubscription(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMySubscriptionQueryResult = NonNullable<Awaited<ReturnType<typeof getMySubscription>>>
export type GetMySubscriptionQueryError = ErrorType<UnauthorizedResponse>


export function useGetMySubscription<TData = Awaited<ReturnType<typeof getMySubscription>>, TError = ErrorType<UnauthorizedResponse>>(
 params: undefined |  GetMySubscriptionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMySubscription>>,
          TError,
          Awaited<ReturnType<typeof getMySubscription>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMySubscription<TData = Awaited<ReturnType<typeof getMySubscription>>, TError = ErrorType<UnauthorizedResponse>>(
 params?: GetMySubscriptionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMySubscription>>,
          TError,
          Awaited<ReturnType<typeof getMySubscription>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMySubscription<TData = Awaited<ReturnType<typeof getMySubscription>>, TError = ErrorType<UnauthorizedResponse>>(
 params?: GetMySubscriptionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller's own subscription for a product
 */

export function useGetMySubscription<TData = Awaited<ReturnType<typeof getMySubscription>>, TError = ErrorType<UnauthorizedResponse>>(
 params?: GetMySubscriptionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMySubscription>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMySubscriptionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Charges the caller's wallet, grants or extends the entitlement, and records the purchase — one transaction, so a charge cannot stand without the subscription it paid for.

Buying while a subscription is still running EXTENDS it from its current expiry, not from now: renewing early must not throw away time already paid for. Lifetime supersedes everything and cannot be extended.

 * @summary Buy or extend a subscription from the FXNod wallet
 */
export const purchaseSubscription = (
    subscriptionPurchaseRequest: BodyType<SubscriptionPurchaseRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SubscriptionPurchaseResponse>(
      {url: `/api/v1/wallet/subscriptions/purchase`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: subscriptionPurchaseRequest, signal
    },
      options);
    }
  


export const getPurchaseSubscriptionMutationOptions = <TError = ErrorType<UnauthorizedResponse | Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseSubscription>>, TError,{data: BodyType<SubscriptionPurchaseRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof purchaseSubscription>>, TError,{data: BodyType<SubscriptionPurchaseRequest>}, TContext> => {

const mutationKey = ['purchaseSubscription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof purchaseSubscription>>, {data: BodyType<SubscriptionPurchaseRequest>}> = (props) => {
          const {data} = props ?? {};

          return  purchaseSubscription(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PurchaseSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof purchaseSubscription>>>
    export type PurchaseSubscriptionMutationBody = BodyType<SubscriptionPurchaseRequest>
    export type PurchaseSubscriptionMutationError = ErrorType<UnauthorizedResponse | Error | ValidationErrorResponse>

    /**
 * @summary Buy or extend a subscription from the FXNod wallet
 */
export const usePurchaseSubscription = <TError = ErrorType<UnauthorizedResponse | Error | ValidationErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseSubscription>>, TError,{data: BodyType<SubscriptionPurchaseRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof purchaseSubscription>>,
        TError,
        {data: BodyType<SubscriptionPurchaseRequest>},
        TContext
      > => {

      const mutationOptions = getPurchaseSubscriptionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    