/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  PartnerEarningsResponse,
  PartnerListResponse,
  ReferralCodeResponse,
  ReferralStatsResponse,
  ReferralTreeResponse,
  UnauthorizedResponse
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get or create the user's referral code
 */
export const getOrCreateReferralCode = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ReferralCodeResponse>(
      {url: `/api/v1/referrals/code`, method: 'POST', signal
    },
      options);
    }
  


export const getGetOrCreateReferralCodeMutationOptions = <TError = ErrorType<UnauthorizedResponse | Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getOrCreateReferralCode>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getOrCreateReferralCode>>, TError,void, TContext> => {

const mutationKey = ['getOrCreateReferralCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getOrCreateReferralCode>>, void> = () => {
          

          return  getOrCreateReferralCode(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetOrCreateReferralCodeMutationResult = NonNullable<Awaited<ReturnType<typeof getOrCreateReferralCode>>>
    
    export type GetOrCreateReferralCodeMutationError = ErrorType<UnauthorizedResponse | Error>

    /**
 * @summary Get or create the user's referral code
 */
export const useGetOrCreateReferralCode = <TError = ErrorType<UnauthorizedResponse | Error>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getOrCreateReferralCode>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getOrCreateReferralCode>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getGetOrCreateReferralCodeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get the user's referral tree
 */
export const getReferralTree = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ReferralTreeResponse>(
      {url: `/api/v1/referrals/tree`, method: 'GET', signal
    },
      options);
    }
  



export const getGetReferralTreeQueryKey = () => {
    return [
    `/api/v1/referrals/tree`
    ] as const;
    }

    
export const getGetReferralTreeQueryOptions = <TData = Awaited<ReturnType<typeof getReferralTree>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralTree>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferralTreeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferralTree>>> = ({ signal }) => getReferralTree(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferralTree>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferralTreeQueryResult = NonNullable<Awaited<ReturnType<typeof getReferralTree>>>
export type GetReferralTreeQueryError = ErrorType<UnauthorizedResponse>


export function useGetReferralTree<TData = Awaited<ReturnType<typeof getReferralTree>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralTree>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferralTree>>,
          TError,
          Awaited<ReturnType<typeof getReferralTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferralTree<TData = Awaited<ReturnType<typeof getReferralTree>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralTree>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferralTree>>,
          TError,
          Awaited<ReturnType<typeof getReferralTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferralTree<TData = Awaited<ReturnType<typeof getReferralTree>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralTree>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the user's referral tree
 */

export function useGetReferralTree<TData = Awaited<ReturnType<typeof getReferralTree>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralTree>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferralTreeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get referral + commission stats
 */
export const getReferralStats = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ReferralStatsResponse>(
      {url: `/api/v1/referrals/stats`, method: 'GET', signal
    },
      options);
    }
  



export const getGetReferralStatsQueryKey = () => {
    return [
    `/api/v1/referrals/stats`
    ] as const;
    }

    
export const getGetReferralStatsQueryOptions = <TData = Awaited<ReturnType<typeof getReferralStats>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferralStatsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferralStats>>> = ({ signal }) => getReferralStats(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferralStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReferralStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getReferralStats>>>
export type GetReferralStatsQueryError = ErrorType<UnauthorizedResponse>


export function useGetReferralStats<TData = Awaited<ReturnType<typeof getReferralStats>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferralStats>>,
          TError,
          Awaited<ReturnType<typeof getReferralStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferralStats<TData = Awaited<ReturnType<typeof getReferralStats>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferralStats>>,
          TError,
          Awaited<ReturnType<typeof getReferralStats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReferralStats<TData = Awaited<ReturnType<typeof getReferralStats>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get referral + commission stats
 */

export function useGetReferralStats<TData = Awaited<ReturnType<typeof getReferralStats>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReferralStats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReferralStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * The partner dashboard's headline. Two axes, because a partner asks two different questions: LEVEL is who they were to the earner (level 1 is someone they invited, level 2 is that person's invitee — what "master affiliate" means here, a position rather than a role), and SOURCE is what that person did.

`matrix` is the finest cut; `by_level`, `by_source` and `total` are folds of exactly it, so a breakdown can never contradict the headline. Every figure is already summed server-side: the client renders these and must never add them up, because parsing decimal strings to add them in JavaScript turns commission into a float.

`source_type` is open. A client that meets an unrecognised value should display it rather than drop it — the money is real either way, and new paid products are expected to appear here without a release.
 * @summary The caller's commission, cut by level and by product
 */
export const getPartnerEarnings = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PartnerEarningsResponse>(
      {url: `/api/v1/referrals/earnings`, method: 'GET', signal
    },
      options);
    }
  



export const getGetPartnerEarningsQueryKey = () => {
    return [
    `/api/v1/referrals/earnings`
    ] as const;
    }

    
export const getGetPartnerEarningsQueryOptions = <TData = Awaited<ReturnType<typeof getPartnerEarnings>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPartnerEarnings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPartnerEarningsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPartnerEarnings>>> = ({ signal }) => getPartnerEarnings(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPartnerEarnings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPartnerEarningsQueryResult = NonNullable<Awaited<ReturnType<typeof getPartnerEarnings>>>
export type GetPartnerEarningsQueryError = ErrorType<UnauthorizedResponse>


export function useGetPartnerEarnings<TData = Awaited<ReturnType<typeof getPartnerEarnings>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPartnerEarnings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPartnerEarnings>>,
          TError,
          Awaited<ReturnType<typeof getPartnerEarnings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPartnerEarnings<TData = Awaited<ReturnType<typeof getPartnerEarnings>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPartnerEarnings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPartnerEarnings>>,
          TError,
          Awaited<ReturnType<typeof getPartnerEarnings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPartnerEarnings<TData = Awaited<ReturnType<typeof getPartnerEarnings>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPartnerEarnings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller's commission, cut by level and by product
 */

export function useGetPartnerEarnings<TData = Awaited<ReturnType<typeof getPartnerEarnings>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPartnerEarnings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPartnerEarningsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Sorted by earnings, then by join date — "who is actually producing" is the question this list is opened to answer.

Email is full at level 1, whom the partner invited personally, and masked below it. A partner's invitee's invitee is a stranger to them, and a working address is enough to contact one.

Not paginated: the tree is capped at MAX_REFERRAL_DEPTH and a partner wants their whole team at once.
 * @summary The caller's downline, and what each person has earned them
 */
export const listPartners = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PartnerListResponse>(
      {url: `/api/v1/referrals/partners`, method: 'GET', signal
    },
      options);
    }
  



export const getListPartnersQueryKey = () => {
    return [
    `/api/v1/referrals/partners`
    ] as const;
    }

    
export const getListPartnersQueryOptions = <TData = Awaited<ReturnType<typeof listPartners>>, TError = ErrorType<UnauthorizedResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPartners>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPartnersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPartners>>> = ({ signal }) => listPartners(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPartners>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPartnersQueryResult = NonNullable<Awaited<ReturnType<typeof listPartners>>>
export type ListPartnersQueryError = ErrorType<UnauthorizedResponse>


export function useListPartners<TData = Awaited<ReturnType<typeof listPartners>>, TError = ErrorType<UnauthorizedResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPartners>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPartners>>,
          TError,
          Awaited<ReturnType<typeof listPartners>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPartners<TData = Awaited<ReturnType<typeof listPartners>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPartners>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPartners>>,
          TError,
          Awaited<ReturnType<typeof listPartners>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPartners<TData = Awaited<ReturnType<typeof listPartners>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPartners>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The caller's downline, and what each person has earned them
 */

export function useListPartners<TData = Awaited<ReturnType<typeof listPartners>>, TError = ErrorType<UnauthorizedResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPartners>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPartnersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




