/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import type { SubscriptionProduct } from './subscriptionProduct';
import type { DecimalString } from './decimalString';
import type { AdminPlanRevenue } from './adminPlanRevenue';

export interface AdminSubscriptionSummary {
  product: SubscriptionProduct;
  entitled_count: number;
  lifetime_count: number;
  expired_count: number;
  cancelled_count: number;
  /** Entitled with no purchase behind it - comped or seeded. */
  granted_count: number;
  total_revenue: DecimalString;
  revenue_by_plan: AdminPlanRevenue[];
  /** Non-lifetime subscriptions whose stored expiry falls inside a week. A fact about dates already in the database, not a forecast. */
  expiring_within_7_days: number;
}
