/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision â€” parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import type { AutoHubSetting } from './autoHubSetting';

export interface AutoHubBot {
  bot_id: string;
  name: string;
  tagline: string;
  description: string;
  /** What the bot's page tells a user before they start it, one point per line. */
  guide: string[];
  /** The FXNod contract type every order of this bot is. */
  contract_type: string;
  duration: number;
  duration_unit: string;
  min_markets: number;
  max_markets: number;
  /** Markets a start request for this bot may not name. */
  excluded_symbols: string[];
  /** Where the form starts. Deriv decides at start whether it sells the contract on the markets chosen. */
  suggested_symbols: string[];
  /** Decimal string. */
  min_stake: string;
  default_stake: string;
  default_stop_loss: string;
  default_take_profit: string;
  settings: AutoHubSetting[];
  /** True for a bot that scores entries before it buys them. */
  has_shadow_lane: boolean;
  /** The percentage of each payout Deriv collects for FXNod on this bot's real-money trades. Demo trades carry none. Absent where app routing is off. */
  markup_pct?: string;
}
