/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import type { DecimalString } from './decimalString';

export interface BotLimits {
  max_stake_per_trade?: string;
  max_session_loss?: string;
  max_session_target_profit?: string;
  max_martingale_multiplier?: string;
  max_martingale_steps?: number;
  max_trades_per_session?: number;
  max_run_duration_seconds?: number;
  /** How many bots one user may run at the same time. */
  max_concurrent_runs?: number;
  /** The ceiling on AGGREGATE realised loss across all of a user's active runs, enforced in addition to each run's own session_stop_loss.

It exists because per-run limits alone are only sufficient while one run is allowed at a time: four bots each carrying a $50 stop loss expose the account to $200, while the user configured "$50" believing that was their exposure. Surface this whenever more than one bot is running, or the per-run number on screen understates real risk.
 */
  max_account_session_loss?: DecimalString;
}
