/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision â€” parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import type { BotRiskLimitsStakeMode } from './botRiskLimitsStakeMode';

/**
 * The session envelope. Amounts are decimal STRINGS, not JSON numbers: a stake of 0.1 through a float64 is 0.1000000000000000055, and these end up in NUMERIC columns and broker requests.
Enforced server-side in the worker, never in the browser - a user closing their tab must not disable their own stop loss.

 */
export interface BotRiskLimits {
  stake_per_trade: string;
  /** Required. There is no representation of a run without one. */
  session_stop_loss: string;
  session_target_profit?: string;
  /** Per-contract limit order, where the contract type supports it. */
  take_profit?: string;
  /** Per-contract limit order, distinct from session_stop_loss. */
  stop_loss?: string;
  /** How the stake moves after each settled contract, per market. flat keeps it fixed; martingale multiplies after a loss; gentle_step adds one base stake after a loss and removes one after a win, never below the base; reverse_martingale multiplies after a win and resets after a loss. Absent, martingale_enabled chooses between martingale and flat, as it did before modes existed.
 */
  stake_mode?: BotRiskLimitsStakeMode;
  /** Legacy switch, read only when stake_mode is absent. */
  martingale_enabled?: boolean;
  /** The factor for the multiplying modes (martingale, reverse_martingale). Must exceed 1; gentle_step ignores it.
 */
  martingale_multiplier?: string;
  /** Length of the ladder in every escalating mode. Exhausting it ENDS a martingale run rather than restarting at the base stake, which would hide an unrecovered loss; gentle_step and reverse_martingale reset to the base stake instead.
 */
  martingale_max_steps?: number;
  /** The caller's own ceiling on one stake, applied on top of the platform cap (which still wins). At least stake_per_trade.
 */
  max_stake_per_trade?: string;
  max_trades?: number;
  max_duration_seconds?: number;
}
