/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision â€” parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import type { RunStateParameter } from './runStateParameter';
import type { ListBotRunsAccount } from './listBotRunsAccount';

export type ListBotRunsParams = {
/**
 * Which runs to list. `active` is every run that has not ended (pending, running, paused or stopping), however old; the filter is applied before the page is cut, so it is the way to ask what is running now. Any other value is a 422.
 */
state?: RunStateParameter;
/**
 * Which kind of Deriv account the runs traded on. Applied before the page is cut, like `state`, so a real run is found however many newer demo runs there are. Any other value is a 422.
 */
account?: ListBotRunsAccount;
/**
 * Only runs started at or after this instant (RFC 3339). A run is placed by when it was started, `created_at`, which is also what the listing is ordered by. Applied before the page is cut. A caller filtering by calendar day sends that day's midnight in the user's own time zone.
 */
from?: string;
/**
 * Only runs started before this instant (RFC 3339). It is not included, so one whole day is its midnight as `from` and the next midnight as `to`. A `from` that is not before `to`, or a value that is not a date-time, is a 422.
 */
to?: string;
/**
 * @maximum 100
 */
limit?: number;
offset?: number;
};
