/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import type { DecimalString } from './decimalString';
import type { ManualDepositResponseCreditedAmount } from './manualDepositResponseCreditedAmount';
import type { ManualDepositStatus } from './manualDepositStatus';

export interface ManualDepositResponse {
  id: string;
  user_id: string;
  /** The amount the user claimed. */
  amount: DecimalString;
  /**
   * What was actually paid out, once approved.
   * @nullable
   */
  credited_amount?: ManualDepositResponseCreditedAmount;
  currency: string;
  chain: string;
  tx_hash: string;
  status: ManualDepositStatus;
  created_at: string;
  updated_at: string;
  /** @nullable */
  admin_note?: string | null;
  /** @nullable */
  reviewed_at?: string | null;
}
