/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision â€” parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import type { DecimalString } from './decimalString';
import type { PayoutBatchStatus } from './payoutBatchStatus';
import type { PayoutBatchOutExpectedMarkup } from './payoutBatchOutExpectedMarkup';
import type { PayoutBatchOutSettlementRatio } from './payoutBatchOutSettlementRatio';
import type { PayoutBatchOutCommissionAccrued } from './payoutBatchOutCommissionAccrued';
import type { PayoutBatchOutCommissionPaid } from './payoutBatchOutCommissionPaid';

export interface PayoutBatchOut {
  id: string;
  period: string;
  source: string;
  amount: DecimalString;
  currency: string;
  status: PayoutBatchStatus;
  /** @nullable */
  admin_note?: string | null;
  /**
   * The markup the trading engine had recorded on the month's trades when the payout was recorded - what the amount was measured against. Null on a payout recorded before the measure existed.
   * @nullable
   */
  expected_markup?: PayoutBatchOutExpectedMarkup;
  /**
   * amount / expected_markup, capped at 1 and rounded down to eight places. Every trade-markup commission of the month was paid this share of itself. Null means paid in full.
   * @nullable
   */
  settlement_ratio?: PayoutBatchOutSettlementRatio;
  /** @nullable */
  recorded_by?: string | null;
  /**
   * Filled in once the Referral service has settled the month.
   * @nullable
   */
  commissions_settled?: number | null;
  /** @nullable */
  commission_accrued?: PayoutBatchOutCommissionAccrued;
  /** @nullable */
  commission_paid?: PayoutBatchOutCommissionPaid;
  created_at: string;
  updated_at: string;
}
