/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import type { ProposalResponse } from './proposalResponse';
import type { ProposalStreamFrameAllOf } from './proposalStreamFrameAllOf';

/**
 * A frame from the live proposal WebSocket (`wss://…/ws/proposal`).

OpenAPI 3.0 cannot describe a WebSocket as a path, but the frame still has a wire shape that the frontend must agree with, so it is declared here as a schema. Without it the shape lives only in hand-written TypeScript, which is exactly how `payout_choices` came to be patched into a GENERATED file and silently reverted by the next codegen run.

Everything in ProposalResponse, plus the fields the stream adds. Keep in step with the `out` map in internal/handlers/http/ws.go.

 */
export type ProposalStreamFrame = ProposalResponse & ProposalStreamFrameAllOf;
