/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FXNod Platform API
 * Unified OpenAPI spec for the FXNod backend stack (Auth, Referral, Wallet,
Trading Engine). All traffic enters through the API gateway, which routes
by path prefix to the individual microservices.

## Authentication model (IMPORTANT for client generators)

FXNod verifies JWTs at the **gateway**, not inside each service. As a
frontend client you only ever send:

    Authorization: Bearer <access_token>

The gateway validates that token and injects internal identity headers
(`X-User-Id`, `X-User-Email`) into the upstream request. **Those headers are
NOT part of the public contract** and are intentionally omitted from this
spec so generated clients never require them. User-facing operations are
marked with the `bearerAuth` security scheme.

Service-to-service and admin operations are guarded by a shared
`X-Internal-Token` (the `internalToken` scheme) and are tagged `Internal`.
They are not intended to be called from the browser; exclude the `Internal`
tag when generating the public frontend client.

Monetary / percentage values are represented as JSON **strings**
(`format: decimal`) to preserve precision — parse them with a decimal
library, not a float.

 * OpenAPI spec version: 0.1.0
 */
import type { DecimalString } from './decimalString';
import type { TradeHistoryEntryOutcome } from './tradeHistoryEntryOutcome';
import type { TradeHistoryEntryFinalPayoutAmount } from './tradeHistoryEntryFinalPayoutAmount';
import type { TradeHistoryEntryEntrySpot } from './tradeHistoryEntryEntrySpot';
import type { TradeHistoryEntryExitSpot } from './tradeHistoryEntryExitSpot';
import type { TradeHistoryEntryTickStreamItem } from './tradeHistoryEntryTickStreamItem';

export interface TradeHistoryEntry {
  id: string;
  user_id: string;
  /** @nullable */
  proposal_id?: string | null;
  deriv_contract_id: string;
  platform: string;
  symbol: string;
  frontend_contract_type: string;
  side: string;
  contract_type: string;
  stake_amount: DecimalString;
  payout_amount: DecimalString;
  accrued_markup_amount: DecimalString;
  deriv_settlement_period: string;
  currency: string;
  created_at: string;
  duration_seconds?: number;
  duration_unit?: string;
  /** @nullable */
  growth_rate?: number | null;
  /** @nullable */
  buy_transaction_id?: number | null;
  /** @nullable */
  sell_transaction_id?: number | null;
  /** @nullable */
  outcome?: TradeHistoryEntryOutcome;
  /** @nullable */
  barrier?: string | null;
  /** @nullable */
  final_payout_amount?: TradeHistoryEntryFinalPayoutAmount;
  /** @nullable */
  entry_spot?: TradeHistoryEntryEntrySpot;
  /** @nullable */
  exit_spot?: TradeHistoryEntryExitSpot;
  /** @nullable */
  tick_stream?: TradeHistoryEntryTickStreamItem[] | null;
  /** @nullable */
  commission?: DecimalString | null;
}
